OpsLevel/terraform-provider-opslevel

- .github/workflows/release-v2.yml
This should allow for completely push-button hands off releasing.
> Setup Release V2

- .changes/unreleased/Bugfix-20220617-063927.yaml
- opslevel/resource_opslevel_team_contact.go
> Fix panic on team contact error message

- .changes/unreleased/Feature-20220706-063847.yaml
- examples/data-sources/opslevel_groups/data-source.tf
- opslevel/datasource_opslevel_groups.go
- opslevel/provider.go
Adding datasource to retrieve all groups
Run and tested with all results providing the correct and expected data
> Feature:adding datasource for groups

- .changes/unreleased/Feature-20220714-145008.yaml
- opslevel/datasource_opslevel_team.go
Adding groups to the team datasource to allow for the below to be the output
```  
team = {
alias       = "Team Alias"
group_alias = "Group Name"
group_id    = "Group ID"
id          = "Team ID"
name        = "Team Name"
}
```
> added groups to team data source

- .changes/unreleased/Bugfix-20220919-202506.yaml
- opslevel/resource_opslevel_rubric_level.go
> bugfix for level resource

- .changes/unreleased/Feature-20230112-084306.yaml
- examples/data-sources/opslevel_users/data-source.tf
- opslevel/datasource_opslevel_users.go
- opslevel/provider.go
> Add datasource for users

- .changes/unreleased/Bugfix-20230112-154223.yaml
- opslevel/schema_checks.go
Based off custom actions branch to get latest changes, can be switched over to main once that branch is merged.
> Update to check notes

- .github/workflows/tests.yml
- Taskfile.yml
> update ci workflow

- .changes/unreleased/Feature-20230912-152914.yaml
- examples/data-sources/opslevel_webhook_action/data-source.tf
- opslevel/datasource_opslevel_webhook_action.go
https://github.com/OpsLevel/team-platform/issues/39
Add webhook action data source
> add webhook action data source

- examples/resources/opslevel_service_tag/resource.tf
- examples/resources/opslevel_team_tag/resource.tf
- opslevel/resource_opslevel_service_tag.go
- opslevel/resources_opslevel_team_tag.go
Resolves https://github.com/OpsLevel/team-platform/issues/46
> tag resource specific deprecation

- .changes/unreleased/Bugfix-20231030-115818.yaml
- Taskfile.yml
- opslevel/resource_opslevel_check_service_ownership.go
- workspace/Taskfile.yml
[#127](https://github.com/OpsLevel/team-platform/issues/127)
Bugfix, reinstate `ANY` as a valid service ownership check contact type for the terraform provider.
Undo earlier update to local plugin directory in Taskfile.
1. Make `main.tf`
```tf
resource "opslevel_check_service_ownership" "example" {
name                   = "foo"
enabled                = true
category               = data.opslevel_rubric_category.example.id
level                  = data.opslevel_rubric_level.example.id
owner                  = data.opslevel_team.example.id
filter                 = data.opslevel_filter.example.id
notes                  = "Optional additional info on why this check is run or how to fix it"
require_contact_method = true
contact_method         = "ANY"  # <-- this is the interesting part …
```
> add ANY to contact type list in check_service_ownership

- .changes/unreleased/Feature-20231109-111446.yaml
- .changes/unreleased/Removed-20231109-113736.yaml
- README.md
- examples/provider/provider.tf
- examples/resources/opslevel_service/resource.tf
- examples/resources/opslevel_team/resource.tf
- opslevel/resource_opslevel_team.go
https://github.com/OpsLevel/team-platform/issues/134
```
$ cat main.tf
resource "opslevel_team" "complex_team" {
name             = "complex tf team"
aliases = ["complex_team"]
member {
email = "taimoor+orange@opslevel.com"
role = "contributor"
}   
member {
email = "kyle+orange@opslevel.com"
role = "manager"
}
}
```
```
$ task apply
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
+ create
+ resource "opslevel_team" "complex_team" {
+ alias        = (known after apply)
+ aliases      = [
+ "complex_team",
]
+ name         = "complex tf team"
+ member {
+ email = …
```
> Assign members with roles

- .changes/unreleased/Bugfix-20231110-143636.yaml
- opslevel/datasource_opslevel_domain.go
- opslevel/datasource_opslevel_domains.go
- opslevel/datasource_opslevel_scorecards.go
- opslevel/datasource_opslevel_system.go
- opslevel/datasource_opslevel_systems.go
- opslevel/resource_opslevel_domain.go
- opslevel/resource_opslevel_infra.go
- opslevel/resource_opslevel_scorecard.go
- opslevel/resource_opslevel_system.go
- opslevel/resource_opslevel_team.go
[#145](https://github.com/OpsLevel/team-platform/issues/145) - partial fix
- Get updated `UserIdentifier` with pointer fields from `NewUserIdentifier()`. This partially resolves an [update bug](https://github.com/OpsLevel/opslevel-go/pull/295#issuecomment-1806235778)
- Fix Owner.Id retrieval after removing EntityOwner
1. Define `opslevel_team` in `main.tf`
```tf
resource "opslevel_team" "brisketz" {
name             = "brisketz"
responsibilities = "Cook for temperature, not time"
member {
email = "pit-boss@example.com"
role  = "manager"
}
}
```
2. `terraform apply`
```tf
+ create
+ resource "opslevel_team" …
```
> Use updated UserIdentifier

- .github/workflows/changie-gen.yml
- .github/workflows/dependabot-labels.yml
- .github/workflows/tests.yml
> update ci to make auto-changie logs work

- .changes/unreleased/Removed-20240103-122630.yaml
- opslevel/resource_opslevel_user.go
Undo a change made in https://github.com/OpsLevel/terraform-provider-opslevel/pull/180.
> Restore skip_welcome_email in User resource

- opslevel/datasource_opslevel_domain.go
- opslevel/resource_opslevel_check_custom_event.go
- opslevel/resource_opslevel_check_has_recent_deploy.go
- opslevel/resource_opslevel_check_service_ownership.go
- opslevel/resource_opslevel_integration_aws.go
- opslevel/resource_opslevel_scorecard.go
- opslevel/resource_opslevel_trigger_definition.go
- opslevel/schema_checks.go
Set the `identifier` field for the Domain datasource to `Required` since, AFAICT, this is needed.
> mark identifier in Domain datasource as required

- Taskfile.yml
Fix how `task setup` was failing locally
`task setup`
> fix task setup, update submodule hash

- Taskfile.yml
- opslevel/provider.go
> fix API TOKEN setting

- .changes/unreleased/Bugfix-20240321-140012.yaml
- opslevel/schema_checks.go
[Terraform bug - cannot update custom event checks once they are created, gets error with 'id' Invalid global id ''](https://github.com/OpsLevel/team-platform/issues/228)
TBD....
Tested in orange
Start with:
```tf
data "opslevel_rubric_category" "security" {
filter {
field = "name"
value = "Security"
}
}
data "opslevel_rubric_level" "good" {
filter {
field = "name"
value = "Good"
}
}
data "opslevel_team" "platform" {
alias = "platform"
}
data "opslevel_filter" "everything_except_templates" {
filter {
field = "name"
value = "All Services"
}
}
resource "opslevel_check_tag_defined" "data_classification_defined" {
name      = "Data Classification Tagged"
enabled   = false
enable_on = "2024-10-01T00:00:00.00000Z"
category  = data.opslevel_rubric_category.security.id
level     = …
```
> provide id to opslevel.CheckUpdateInput struct

- .changes/unreleased/Bugfix-20240325-121619.yaml
- opslevel/datasource_opslevel_domain.go
- opslevel/resource_opslevel_domain.go
Update Domain's `Aliases` to `ManagedAliases`. See [updated field here](https://github.com/OpsLevel/opslevel-go/blob/main/domain.go#L15)
> update domain aliases field

- opslevel/datasource_opslevel_integration.go
- opslevel/provider.go
- tests/data_sources.tf
- tests/datasource_integration.tftest.hcl
- tests/mock_datasource/integration.tfmock.hcl
```
data "opslevel_integration" "pd_opslevel" {
filter {
field = "name"
value = "PagerDuty - opslevel-prod"
}
}
data "opslevel_integration" "slack_opslevel" {
filter {
field = "id"
value = "Z2lkOi8vb3BzbGV2ZWwvSW50ZWdyYXRpb25zOjpTbGFja0ludGVncmF0aW9uLzI2"
}
}
output "slack_opslevel_integration" {
value = data.opslevel_integration.slack_opslevel
}
output "slack_opslevel_pagerduty" {
value = data.opslevel_integration.pd_opslevel
}
```
```
+ slack_opslevel_integration = {
+ filter = {
+ field = "id"
+ value = "Z2lkOi8vb3BzbGV2ZWwvSW50ZWdyYXRpb25zOjpTbGFja0ludGVncmF0aW9uLzI2"
}
+ id     = "Z2lkOi8vb3BzbGV2ZWwvSW50ZWdyYXRpb25zOjpTbGFja0ludGVncmF0aW9uLzI2"
+ name   = "Slack - OpsLevel"
}
+ slack_opslevel_pagerduty   = {
+ …
```
> Support integration datasource

- opslevel/datasource_opslevel_repository.go
- opslevel/provider.go
- tests/data_sources.tf
- tests/datasource_repository.tftest.hcl
- tests/mock_datasource/repository.tfmock.hcl
```
data "opslevel_repository" "rep1" {
alias = "github.com:OpsLevel/opslevel-go"
}
data "opslevel_repository" "rep2" {
id = "Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRodWIvMTU2Mzk"
}
output "o1" {
value = data.opslevel_repository.rep1
}
output "o2" {
value = data.opslevel_repository.rep2
}
```
```
data.opslevel_repository.rep1: Reading...
data.opslevel_repository.rep2: Reading...
data.opslevel_repository.rep2: Read complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRodWIvMTU2Mzk]
data.opslevel_repository.rep1: Read complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRodWIvMTU2Mzk]
+ o1 = {
+ alias = "github.com:OpsLevel/opslevel-go"
+ id    = …
```
> add repository datasource

- Taskfile.yml
> unset nilaway in Taskfile

- opslevel/provider.go
- opslevel/resource_opslevel_webhook_action.go
- tests/mock_resource/webhook_action.tfmock.hcl
- tests/resource_webhook_action.tftest.hcl
- tests/resources.tf
[webhook_action public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/webhook_action)
Changes:
- Add `webhook_action` resource, with tests
```tf
resource "opslevel_webhook_action" "test" {
description = "Test - Pages the On Call"
headers = {
accept        = "application/vnd.pagerduty+json;version=2"
authorization = "Token token=XXXXXXXXXXXXXX"
content-type  = "application/json"
from          = "foo@opslevel.com"
}
method  = "POST"
name    = "Test - PD Webhook Action"
payload = <<EOT
{
"incident":
{
"type": "incident",
"title": "{{manualInputs.IncidentTitle}}",
"service": {
"id": "{{ service | tag_value: 'pd_id' }}",
"type": "service_reference"
},
"body": {
"type": "incident_body",
"details": …
```
> add webhook_action resource, with tests

- opslevel/resource_opslevel_webhook_action.go
- opslevel/terraform_type_conversions.go
I missed this final commit in the [last PR](https://github.com/OpsLevel/terraform-provider-opslevel/pull/262). I tophatted everything with this code locally and forgot push these changes
> add missed updates to webhook_action

- opslevel/resource_opslevel_service.go
Exact copy of [other PR](https://github.com/OpsLevel/terraform-provider-opslevel/pull/265) that won't merge because Github had an incident
> handle id or alias case outside of NewServiceResourceModel

- opslevel/provider.go
- opslevel/resource_opslevel_service_tag.go
- opslevel/resources_opslevel_team_tag.go
- tests/mock_resource/team_tag.tfmock.hcl
- tests/resource_team_tag.tftest.hcl
- tests/resources.tf
https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/team_tag
Have an existing team. Config:
```
resource "opslevel_team_tag" "team_tag_1" {
key   = "hello"
value = "world"
team  = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQxMg"
}
resource "opslevel_team_tag" "team_tag_2" {
key        = "hello_with_alias"
value      = "world_with_alias"
team_alias = "team_platform_3"
}
```
```
- resource "opslevel_team_tag" "team_tag_1" {
- id    = "Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNTIyMDY1" -> null
- key   = "hello" -> null
- team  = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQxMg" -> null
- value = "world" -> null
}
- resource "opslevel_team_tag" "team_tag_2" {
- id         = …
```
> Add team tag resource

- opslevel/provider.go
- opslevel/resource_opslevel_team_contact.go
- tests/mock_resource/team_contact.tfmock.hcl
- tests/resource_team_contact.tftest.hcl
- tests/resources.tf
https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/team_contact
Config file:
```
resource "opslevel_team_contact" "tc_1" {
name = "Slack Channel"
team = "team_platform_3"
type = "slack"
value = "#team-platform-3"
}
resource "opslevel_team_contact" "tc_2" {
name = "Internal Email Address"
team = "team_platform_3"
type = "email"
value = "team-platform-3@opslevel.com"
}
```
```
+ resource "opslevel_team_contact" "tc_1" {
+ name         = "Slack Channel"
+ team         = "team_platform_3"
+ type         = "slack"
+ value        = "#team-platform-3"
}
+ resource "opslevel_team_contact" "tc_2" { …
```
> Add team contact resource

- opslevel/provider.go
- opslevel/resource_opslevel_check_git_branch_protection.go
- tests/mock_resource/check_git_branch_protection.tfmock.hcl
- tests/resource_check_git_branch_protection.tftest.hcl
- tests/resources.tf
This add the git branch protection check
Create
```bash
+ resource "opslevel_check_git_branch_protection" "example" {
+ enable_on    = "2022-05-23T14:14:18.782000Z"
+ enabled      = false
}
```
Update
```bash
~ resource "opslevel_check_git_branch_protection" "example" {
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpHaXRCcmFuY2hQcm90ZWN0aW9uLzI0MTcz"
~ level        = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw" -> "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIx"
}
```
update - remove enable_on
```bash
~ resource …
```
> Add check git branch protection

- opslevel/provider.go
- opslevel/resource_opslevel_check_repository_integrated.go
- tests/resource_check_repository_integrated.tftest.hcl
- tests/resources.tf
Add repo integrated check
Create
```bash
+ resource "opslevel_check_repository_integrated" "example" {
}
```
Update
```bash
~ resource "opslevel_check_repository_integrated" "example" {
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpIYXNSZXBvc2l0b3J5LzI0MTc3"
~ name         = "foo" -> "foobar"
}
```
Delete
```
- resource "opslevel_check_repository_integrated" "example" {
- category    = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1" -> null
- description = "Verifies that the service has a repository …
```
> Add Repository Integrated check

- opslevel/provider.go
- opslevel/resource_opslevel_check_has_recent_deploy.go
- tests/resource_check_has_recent_deploy.tftest.hcl
- tests/resources.tf
Add has recent deploy check
Create
```bash
+ resource "opslevel_check_has_recent_deploy" "example" {
+ days         = 14
+ enabled      = false
}
```
Update
```bash
~ resource "opslevel_check_has_recent_deploy" "example" {
~ days         = 14 -> 7
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpIYXNSZWNlbnREZXBsb3kvMjQxNTQ"
}
```
> has recent deploy check

- opslevel/provider.go
- opslevel/resource_opslevel_check_service_dependency.go
- tests/resource_service_dependency.tftest.hcl
- tests/resources.tf
Add service dependency check
Create
```bash
+ resource "opslevel_check_service_dependency" "example" {
}
```
Update add team
``` bash
~ resource "opslevel_check_service_dependency" "example" {
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpTZXJ2aWNlRGVwZW5kZW5jeS8yNDE2NQ"
+ owner        = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMTcwNQ"
}
```
update remove team
```bash
~ resource "opslevel_check_service_dependency" "example" {
id           = …
```
> Add service dependency check

- opslevel/provider.go
- opslevel/resource_opslevel_check_service_configuration.go
- tests/resources.tf
- tests/resources_check_service_configuration.tftest.hcl
Add service configuration check
Create
```bash
+ resource "opslevel_check_service_configuration" "example" {
}
```
Update add filter
```bash
~ resource "opslevel_check_service_configuration" "example" {
~ description  = "Verifies that the service is maintained though the use of an opslevel.yml service config." -> (known after apply)
+ filter       = "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzQzNjk"
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpIYXNTZXJ2aWNlQ29uZmlnLzI0MTY0"
}
``` …
> Add service configuration check

- opslevel/resource_opslevel_domain.go
- opslevel/resource_opslevel_filter.go
- opslevel/resource_opslevel_rubric_level.go
- opslevel/resource_opslevel_scorecard.go
- opslevel/resource_opslevel_secrets.go
- opslevel/resource_opslevel_service.go
- opslevel/resource_opslevel_trigger_definition.go
- opslevel/resource_opslevel_user.go
- opslevel/resource_opslevel_webhook_action.go
Mostly update pointer types to RefOf to provider a pointer with a empty string (some zero value) to actually unset fields
> fixes to fields during update operations

- .github/workflows/release.yml
> fix syntax in release github workflow

- .github/workflows/release.yml
Last release didn't succeed.
Plan:
-  add this
- run release
- print client payload
- fix release and remove this update
> temp debug release workflow

- .github/workflows/release.yml
> fix release accepting version

- .github/workflows/release.yml
> fix syntax again in release github workflow

- opslevel/resource_opslevel_infra.go
> remove unused code

- opslevel/datasource_opslevel_system.go
> use ComputedStringValue to return null not empty string

- opslevel/datasource_opslevel_service.go
- opslevel/datasource_opslevel_team.go
- tests/datasource_service.tftest.hcl
- tests/datasource_team.tftest.hcl
- tests/mock_datasource/service.tfmock.hcl
- tests/mock_datasource/team.tfmock.hcl
```tf
data "opslevel_service" "platform_repo_alias" {
alias = "platform.repo"
}
data "opslevel_service" "test" {
id = "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS81Njg3Ng"
}
output "platform_repo_alias" {
value = data.opslevel_service.platform_repo_alias
}
output "test" {
value = data.opslevel_service.test
}
data "opslevel_team" "engineering" {
alias = "engineering"
}
data "opslevel_team" "platform" {
id = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5"
}
output "o1" {
value = data.opslevel_team.engineering
}
output "o2" {
value = data.opslevel_team.platform
}
```
```tf
data.opslevel_team.engineering: Read complete after 0s [id=Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMTA5OQ]
data.opslevel_team.platform: Read complete after 0s [id=Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5]
data.opslevel_service.test: Read complete after 1s …
```
> replace custom ObjectTypes in team datasource

- .changes/unreleased/Feature-20240423-100219.yaml
- opslevel/datasource_opslevel_integration.go
- opslevel/datasource_opslevel_integrations.go
- opslevel/datasource_opslevel_integrations_all.go
- opslevel/provider.go
Changes:
- Add `integrations` datasource
```terraform
data "opslevel_integration" "by_id" {
filter {
field = "id"
value = "Z2lkOi8vb3BzbGV2ZWwvSW50ZWdyYXRpb25zOjpFdmVudHM6OkRvY3VtZW50czo6QXBpRG9jSW50ZWdyYXRpb24vMTc4Nw"
}
}
data "opslevel_integration" "by_name" {
filter {
field = "name"
value = "Terraform"
}
}
data "opslevel_integrations" "all" {
}
output "all" {
value = data.opslevel_integrations.all
}
output "by_id" {
value = data.opslevel_integration.by_id
}
output "by_name" {
value = data.opslevel_integration.by_name
}
```
```terraform
data.opslevel_integrations.all: Reading...
data.opslevel_integration.by_name: Reading...
data.opslevel_integration.by_id: Reading... …
```
> add integrations datasource back in

- .changes/unreleased/Feature-20240423-093114.yaml
- opslevel/datasource_opslevel_rubric_level.go
- opslevel/datasource_opslevel_rubric_levels.go
- opslevel/datasource_opslevel_rubric_levels_all.go
- opslevel/provider.go
Changes:
- Add `rubric_levels` datasource
```terraform
data "opslevel_rubric_levels" "all" {
}
data "opslevel_rubric_level" "by_alias" {
filter {
field = "alias"
value = "good"
}
}
data "opslevel_rubric_level" "by_id" {
filter {
field = "id"
value = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvMTA3"
}
}
data "opslevel_rubric_level" "by_index" {
filter {
field = "index"
value = 4
}
}
data "opslevel_rubric_level" "by_name" {
filter {
field = "name"
value = "amazing 2"
}
}
output "all" {
value = data.opslevel_rubric_levels.all
}
output "level_by_alias" {
value = data.opslevel_rubric_level.by_alias
}
output "level_by_index" {
value = data.opslevel_rubric_level.by_index
}
output "level_by_id" {
value = data.opslevel_rubric_level.by_id
} …
```
> add rubric_levels datasource back in

- opslevel/common.go
- opslevel/datasource_opslevel_repositories_all.go
- opslevel/resource_opslevel_check_alert_source_usage.go
- opslevel/resource_opslevel_check_base.go
- opslevel/resource_opslevel_check_has_documentation.go
- opslevel/resource_opslevel_check_manual.go
- opslevel/resource_opslevel_check_service_ownership.go
- opslevel/resource_opslevel_check_service_property.go
- opslevel/resource_opslevel_check_tool_usage.go
- opslevel/resource_opslevel_filter.go
- opslevel/resource_opslevel_property_definition.go
- opslevel/resource_opslevel_service.go
- opslevel/resource_opslevel_service_tool.go
- opslevel/resource_opslevel_tag.go
- opslevel/resource_opslevel_team_contact.go
- opslevel/resource_opslevel_trigger_definition.go
- opslevel/resource_opslevel_user.go
- opslevel/resource_opslevel_webhook_action.go
- tests/resource_check_service_ownership.tftest.hcl
- tests/resources.tf
[show possible values for enum fields](https://github.com/OpsLevel/team-platform/issues/153)
Include enums in attribute Descriptions
> add enums in attribute Descriptions

- .changes/unreleased/Feature-20240426-164555.yaml
- .changes/unreleased/Feature-20240426-164650.yaml
- opslevel/datasource_opslevel_webhook_action.go
- opslevel/datasource_opslevel_webhook_actions_all.go
- opslevel/provider.go
```
data "opslevel_webhook_action" "an_action" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8yNA"
}
output "single_webhook_action" {
value = data.opslevel_webhook_action.an_action
}
data "opslevel_webhook_actions" "all" {
}
output "all_webhook_actions" {
value = data.opslevel_webhook_actions.all
}
```
```
+ all_webhook_actions   = {
+ webhook_actions = [
+ {
+ aliases     = null
+ description = "Webhook action for Fire Warning Shot, created from the OpsLevel UI"
+ headers     = {}
+ id          = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8yNA"
+ method      = "GET"
+ name        = "Fire Warning Shot Action"
+ payload     = ""
+ url         = "https://google.ca"
},
+ {
+ …
```
> Webhook actions all datasource - add ID, aliases to webhook action datasource

- opslevel/resource_opslevel_check_repository_search.go
- tests/remote/check_manual.tftest.hcl
- tests/remote/check_repository_grep.tftest.hcl
- tests/remote/service.tftest.hcl
- tests/remote/team.tftest.hcl
Update tests to work with previous updates to code. `aliases` was a list type but now is a set type
`task test-integration`
> update tests to match code changes

- .github/workflows/release.yml
> update deprecated goreleaser args in CI

- .github/pull_request_template.md
> update tophatting section of pull request template

- .changes/unreleased/Refactor-20240710-105829.yaml
- opslevel/datasource_opslevel_domain.go
- opslevel/datasource_opslevel_domains_all.go
- opslevel/datasource_opslevel_scorecard.go
- opslevel/datasource_opslevel_scorecards_all.go
- opslevel/datasource_opslevel_service.go
- opslevel/datasource_opslevel_system.go
- opslevel/datasource_opslevel_systems_all.go
- opslevel/datasource_opslevel_webhook_action.go
- opslevel/datasource_opslevel_webhook_actions_all.go
- opslevel/resource_opslevel_check_repository_file.go
- opslevel/resource_opslevel_check_repository_grep.go
- opslevel/resource_opslevel_domain.go
- opslevel/resource_opslevel_integration_aws.go
- opslevel/resource_opslevel_scorecard.go
- opslevel/resource_opslevel_system.go
- opslevel/resource_opslevel_trigger_definition.go
- opslevel/terraform_type_conversions.go
Simplify `OptionalStringListValue()` and as a result much of the code calling it.
[task test-integration](https://github.com/OpsLevel/terraform-provider-opslevel/actions/runs/9911184718/job/27383271780)
> update OptionalStringListValue and refactor code using it

- .changes/unreleased/Bugfix-20240716-102636.yaml
> add changie log

- .goreleaser.yml
- Taskfile.yml
> fix release version

- .changes/unreleased/Dependency-20240724-134715.yaml
- .changes/unreleased/Dependency-20240724-134750.yaml
- .changes/unreleased/Dependency-20240724-134806.yaml
- go.mod
- go.sum
- tests/local/resource_filter.tftest.hcl
- tests/local/resources.tf
[unable to set owner_ids to id reference nor int](https://github.com/OpsLevel/terraform-provider-opslevel/issues/381)
Bump module version to go 1.22
Update opslevel-go submodule hash (the actual fix is there)
```tf
data "opslevel_domains" "test" {}
data "opslevel_filters" "test" {}
data "opslevel_systems" "test" {}
data "opslevel_teams" "test" {}
resource "opslevel_filter" "all_predicates" {
for_each = local.all_predicates
name = each.key
predicate {
key      = each.value.key
key_data = each.value.key_data
type     = each.value.type
value    = each.value.value
}
}
locals {
string_predicates = setproduct(
["aliases", "framework", "language", "name", "product"],
[
"contains",
"does_not_contain",
"does_not_equal",
"does_not_exist",
"does_not_match_regex",
"ends_with",
"equals",
"exists", …
```
> bump module to go 1.22, update opslevel-go submodule hash

- tests/README.md
> add test README

- .changes/unreleased/Dependency-20240820-082255.yaml
- go.mod
- go.sum
- opslevel/datasource_opslevel_domain.go
Bump TF Framework version and demonstrate that embedded struct tags work. Paves way for refactoring
```tf
data "opslevel_domains" "all" {}
data "opslevel_domain" "one" {
identifier = data.opslevel_domains.all.domains[0].id
}
output "all" {
value = data.opslevel_domains.all.domains
}
output "one" {
value = data.opslevel_domain.one
}
```
> bump tf framework version, introduce embedded structs

- Taskfile.yml
Enable interactive debugging with breakpoints 🔬 
[Docs here](https://developer.hashicorp.com/terraform/plugin/debugging)
After setting up `workspace/main.tf`
1. In first terminal run `task debug-start` (or `task dbg1`)
2. In second terminal run `task debug-attach` (or `task dbg2`)
- Set breakpoints, try `b <path-to-file>:<line number>`
3. In third terminal run `task debug-plan` or `task debug-apply`
4. Return to second terminal and press `c` to continue
> add debug tasks for interactive debugging

- .github/workflows/tests-integration.yml
> clone submodules during integration testing

- .github/workflows/tests-integration.yml
> add OpsLevel CLI needed in TF integration tests

- taskfiles/Debug.yml
> conveniently install dlv for debugging

- opslevel/resource_opslevel_check_has_documentation.go
Resolves #
Update description so searching for the term "API Docs" in the terraform documentation will surface the check_has_documentation resource.
> update description for check_has_documentation

- .changes/unreleased/Added-20250415-140510.yaml
- examples/resources/opslevel_trigger_definition/resource.tf
- examples/resources/opslevel_webhook_action/resource.tf
- go.mod
- go.sum
- opslevel/common.go
- opslevel/resource_opslevel_trigger_definition.go
- opslevel/resource_opslevel_webhook_action.go
- tests/remote/trigger_definition.tftest.hcl
- tests/remote/trigger_definition/main.tf
- tests/remote/trigger_definition/variables.tf
- tests/remote/webhook_action.tftest.hcl
- tests/remote/webhook_action/main.tf
- tests/remote/webhook_action/variables.tf
> add Async & Approval config to webhook action
