OpsLevel/terraform-provider-opslevel

examples/resources/opslevel_filter/resource.tf, opslevel/resource_opslevel_filter.go
Hello!
This adds:
* The list of valid values for the `type` parameter in filters.
* Fixes a small typo on the `key_data` description.
* Adds a filter example where tags are used.
=> Improved filters docs

.changes/unreleased/Feature-20220516-075238.yaml, opslevel/resource_opslevel_check_repository_file.go
The changes to opslevel-go are here - https://github.com/OpsLevel/opslevel-go/pull/56
=> Add support for useAbsoluteRoot in repo file check

.changes/unreleased/Feature-20220807-150331.yaml, examples/resources/opslevel_check_has_documentation/import.sh, examples/resources/opslevel_check_has_documentation/resource.tf, go.mod, go.sum, opslevel/provider.go, opslevel/resource_opslevel_check_has_documentation.go
Adding the HasDocumentation Check, which depends on this [PR](https://github.com/OpsLevel/opslevel-go/pull/75) to opslevel-go first. Testing locally with `replace github.com/opslevel/opslevel-go/v2022 => ../opslevel-go/` (seemed easier than git submodules), looks like it works!
=> Add HasDocumentation Check

.changes/unreleased/Feature-20220922-100247.yaml, docs/index.md, opslevel/provider.go
- adding ability to set a custom value for the client timeout value in calls to GQL
This is being added due to the current continual timeout when trying to retrieve all team and service date using datasources.
=> adding override feature for client timeout

.changes/unreleased/Bugfix-20221019-211141.yaml, opslevel/common.go
When doing
```
resource "opslevel_filter" "foo" {
name = "foo"
predicate {
key      = "tags"
type     = "contains"
key_data = "foo"
value = "bar"
}
}
```
the data is correct in OpsLevel
but when doing
```
resource "opslevel_filter" "test" {
name = "foo"
predicate {
key      = "tags"
type     = "contains"
key_data = "foo"
value = <<-EOT
bar
EOT
}
}
```
in OpsLevel you get a value of `bar ` (extra space at the end)
This fixes that.
=> Fixes #5152

.changes/unreleased/Bugfix-20221215-055650.yaml, opslevel/datasource_opslevel_service.go
Fixes #48
We were not properly storing the field into the state.  Which is odd because we didn't do this in the resource for `opslevel_service` - https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/opslevel/resource_opslevel_service.go#L270
=> Bugfix for nil pointer deference

.github/workflows/tests.yml, CONTRIBUTING.md, examples/resources/opslevel_user/resource.tf, go.mod, go.sum, opslevel/provider_test.go, opslevel/resource_opslevel_user_test.go, test
Sets up the basis for running integration Acceptance tests.  These tests directly hit an opslevel account but perform cleanups.  We should beable to use these as a way to full flush water through the pipes before a release.
=> Acceptance Testing

examples/resources/opslevel_integration_aws/resource.tf
Adds the following permissions grants to the AWS policy example:
```
"s3:GetBucketPolicyStatus",
"s3:GetBucketVersioning",
```
OpsLevel requires both of these IAM grants to ensure we can sync certain information about s3 buckets.
=> Update AWS IAM policy to include required S3 permissions

.changes/unreleased/Feature-20230515-115351.yaml, docs/resources/trigger_definition.md, go.mod, go.sum, opslevel/resource_opslevel_trigger_definition.go
This adds support for EntityType in Custom Actions.
Upstream change in opslevel-go is [here](https://github.com/OpsLevel/opslevel-go/pull/196)
=> Add support for EntityType in Custom Actions

.changes/unreleased/Feature-20230810-144653.yaml, go.mod, go.sum
Support more filter predicate keys and types that were added to opslevel-go: https://github.com/OpsLevel/opslevel-go/pull/226
```
$ cat workspace/test.tf
resource "opslevel_filter" "f1" {
name = "foo"
predicate {
key      = "filter_id"
type     = "matches"
key_data = "some-other-filter"
}
}
resource "opslevel_filter" "f2" {
name = "foo"
predicate {
key      = "filter_id"
type     = "does_not_match"
key_data = "some-other-filter"
}
}
resource "opslevel_filter" "f3" {
name = "foo"
predicate {
key      = "name"
type     = "does_not_match_regex"
key_data = "^opslevel"
}
}%                                                                                                                                                                                                                    
$ ./plan …
```
=> upgrade opslevel-go version to v2023.07.28

.changes/unreleased/Feature-20230824-161018.yaml, .github/workflows/tests.yml, Taskfile.yml, examples/resources/opslevel_scorecard/import.sh, examples/resources/opslevel_scorecard/resource.tf, opslevel/provider.go, opslevel/resource_opslevel_scorecard.go
https://github.com/OpsLevel/team-platform/issues/33
Relies on https://github.com/OpsLevel/opslevel-go/pull/233
Step 1: wrote terraform file
```
resource "opslevel_team" "platform_team" {
name = "platform"
}
resource "opslevel_filter" "rds_filter" {
name = "rds apps"
predicate {
key      = "tags"
key_data = "db"
type     = "equals"
value = "rds"
}
}
resource "opslevel_scorecard" "rds_scorecard" {
name = "rds scorecard"
description = "scorecard for apps using rds"
owner_id = opslevel_team.platform_team.id
filter_id = opslevel_filter.rds_filter.id
}
resource "opslevel_scorecard" "min_scorecard" {
name = "minimal scorecard"
owner_id = opslevel_team.platform_team.id
}
```
Step 2: terraform apply
```
Terraform used the selected providers to generate the following execution plan. Resource …
```
=> Support scorecards

CONTRIBUTING.md, go.mod
Removed old way of setting up go workspace in favor or `task workspace`
Proven to work in CI see [this success story](https://github.com/OpsLevel/terraform-provider-opslevel/pull/105)
=> update CONTRIBUTING docs, go.mod

.changes/unreleased/Feature-20230831-112138.yaml, opslevel/datasource_opslevel_scorecard.go, opslevel/datasource_opslevel_scorecards.go, opslevel/provider.go
https://github.com/OpsLevel/team-platform/issues/66
```
$ cat scorecard.tf
data "opslevel_scorecards" "all_scorecards" {
}
output "fetch_all_scorecards" {
value = data.opslevel_scorecards.all_scorecards
}
data "opslevel_scorecard" "my-scorecard" {
identifier = "test2"
}
output "my-scorecard" {
value = data.opslevel_scorecard.my-scorecard
}
$ task tf-plan
+ fetch_all_scorecards = {
+ aliases        = [
+ [
+ "test_scorecard",
],
+ [
+ "rds_scorecard",
],
+ [
+ "test2",
],
]
+ descriptions   = [
+ "test description",
+ "",
+ "scorecard no filter",
]
+ filter_ids     = [
+ "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzM1OA",
+ "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzI1NzQ",
+ "",
]
+ id             = "1693420797"
+ ids            = [
+ "Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzYwNw",
+ …
```
=> Scorecard datasource

examples/resources/opslevel_infrastructure/resource.tf
example_2 referenced `devs` while the data in the example is labeled `foo`. Updated example_2 to reference `foo` instead.
=> reference foo in example_2 owner field

docs/resources/filter.md, opslevel/resource_opslevel_filter.go
* Update resource_opslevel_filter.go with updated predicate type values `match`, `does_not_match`
=> resource_opslevel_filter: add matches/does_not_match to type values

.changes/unreleased/Feature-20231006-093301.yaml, examples/resources/opslevel_filter/resource.tf, opslevel/common.go, opslevel/resource_opslevel_check_service_ownership.go, opslevel/resource_opslevel_filter.go
https://github.com/OpsLevel/team-platform/issues/95
Added example to show how to use this new field
```tf
resource "opslevel_filter" "case_sensitive" {
name = "foo"
predicate {
key            = "tags"
type           = "equals"
key_data       = "my-custom-tag"
value          = "hello-world"
case_sensitive = true
}
}
```
=> Add support for case sensitive on filter predicates

examples/resources/opslevel_tag/resource.tf
Updating examples for `opslevel_tag`s. 
- `resource_id` should be `resource_identifier`
- Added examples for `InfrastructureResource` and `User` resources
N/A - will be reflected [here](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/tag)
=> fix typos, add User and InfrastructureResource examples

.changes/unreleased/Feature-20231017-135010.yaml, examples/resources/opslevel_team/resource.tf, opslevel/datasource_opslevel_team.go, opslevel/resource_opslevel_team.go
[#118](https://github.com/OpsLevel/team-platform/issues/118)
Add `parent_team` field to `opslevel_team` resource.
Update commit hash to submodule (needs one more update after `opslevel-go` PR is merged) 
Using this (slightly edited) `main.tf`
```
data "opslevel_group" "foo" {
identifier = "bar-group"
}
data "opslevel_team" "parent" {
alias = "platform"
}
resource "opslevel_team" "tf-example" {
name             = "terraform-test-team"
manager_email    = "themanager@example.com"
members          = ["themanager@example.com", "teammember@example.com"]
responsibilities = "Important things"
aliases          = ["bar", "baz"]
group            = data.opslevel_group.foo.alias
parent_team      = data.opslevel_team.parent.alias
}
output "team" {
value = opslevel_team.tf-example.id
}
```
1. Terraform …
=> add parent_team field to opslevel_team resource

.changes/unreleased/Deprecated-20231024-125941.yaml, .changes/unreleased/Refactor-20231023-150009.yaml, README.md, docs/data-sources/service.md, docs/index.md, docs/resources/service.md, examples/provider/provider.tf, examples/resources/opslevel_service/resource.tf, opslevel/datasource_opslevel_service.go, opslevel/resource_opslevel_service.go
https://github.com/OpsLevel/opslevel-go/issues/276
... See latest comment for most up to date tophatting. Bug mentioned below still applies. 
**The resource gets created fine and I can see it on the website. Same thing happens when updating the name of the service. A ticket exists for this: https://github.com/OpsLevel/terraform-provider-opslevel/issues/129 we closed it but I think we should re-open.**
=> deprecate ownerAlias

.changes/unreleased/Bugfix-20231106-131911.yaml, opslevel/datasource_opslevel_service.go, opslevel/resource_opslevel_service.go
This should fix https://github.com/OpsLevel/terraform-provider-opslevel/issues/129 and https://github.com/OpsLevel/team-platform/issues/135 where slugs were being treated as aliases.
Uncommented each block one by one. Notice no errors are thrown, slugs are not treated as aliases!
```
```
```
~/repos/terraform-provider-opslevel/workspace managedalias ❯ task apply                                                                                                    6s Ruby 3.0.0 01:17:45 pm
task: [terraform-command] terraform -chdir=/Users/taimoorahmad/repos/terraform-provider-opslevel/workspace apply 
+ create
+ …
```
=> Managed Aliases on Service

.changes/unreleased/Bugfix-20231107-162846.yaml, opslevel/resource_opslevel_team_contact.go
=> remove unneeded HasChange checks in opslevel_team_contact updates

.changes/unreleased/Bugfix-20231107-162955.yaml, .changes/unreleased/Feature-20231107-163024.yaml, opslevel/resource_opslevel_infra.go, opslevel/resource_opslevel_service.go
https://github.com/OpsLevel/team-platform/issues/112
Allow aliases to be managed on infra resources just like they are managed on services. 
**NOTE** that unlike services, infra resources don't have a slug/friendly_id that is placed inside the aliases array. So using `ManagedAliases` is not necessary! 
Create infra resource with no aliases:
```
~/repos/terraform-provider-opslevel/workspace infraresaliases !2 ❯ cat main.tf && task apply                                                                                                                                                                        5s Ruby 3.0.0 04:55:10 pm
resource "opslevel_infrastructure" "new_tf_infra" {
schema = "Database"
name = "a new infra res made in tf"
})
provider_data {
account = "dev"
}
} …
```
=> Support for aliases on  Infrastructure Resources

.changes/unreleased/Bugfix-20231109-171226.yaml, opslevel/resource_opslevel_system.go
A bug with creating systems was identified here: https://github.com/OpsLevel/opslevel-go/pull/295
1. Create system with owner
2. Change owner
3. Delete owner
```
~/repos/terraform-provider-opslevel/workspace system-patches ❯ task apply                                                                                                                                                                                                                                              х 200 Ruby 3.0.0 01:22:37 PM
task: [terraform-command] terraform -chdir=/Users/taimoorahmad/repos/terraform-provider-opslevel/workspace apply 
+ create
Terraform will perform the …
```
=> System - allow unsetting owner, identified bug where lots of fields cannot be unset

.changes/unreleased/Bugfix-20231123-142256.yaml, opslevel/resource_opslevel_service.go
https://gitlab.com/jklabsinc/OpsLevel/-/issues/9951
TL;DR customer reported a bug where changing the `owner` field for an `owner_alias` and vice versa causes an error to be shown. That error is caused by the if statement that relies on `GetOk()`. 
All of these pass and there are no errors shown, only deprecation warnings when owner_alias is used.
Create a new service with owner_alias.
```
+ resource "opslevel_service" "bugsv2" {
+ name         = "Bugged Service 2"
+ owner_alias  = "bugging_team"
}
```
Replace the owner_alias with owner.
```
~ resource "opslevel_service" "bugsv2" {
id          = "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS84NzUwOQ"
name        = "Bugged Service 2"
+ …
```
=> Fix owner_alias to owner migration by replacing GetOK() with Get()

.changes/unreleased/Feature-20231129-141715.yaml, opslevel/resource_opslevel_team.go
Some customers are defining Teams in terraform, but are not defining team memberships in their configurations (*.tf files) using `member {}` blocks. They are unable to run this provider because doing so results in all members being unassigned since they are not defined in terraform. 
One option for them is to export their members into their terraform config using the CLI.
The other option is for the terraform provider to only touch Team Memberships if they are defined or were previously defined **at any point before in the configuration.** 
Related, export members from web into terraform using CLI: https://github.com/OpsLevel/cli/pull/206
Related, ability to use `member {}` blocks in terraform: https://github.com/OpsLevel/terraform-provider-opslevel/pull/144
Create the team
```
+ resource …
```
=> Only manage team memberships if they were defined before in the config

.changes/unreleased/Feature-20231129-141715.yaml
TL;DR this PR tried to fix a bug but it has a regression, [details here](https://github.com/OpsLevel/terraform-provider-opslevel/pull/162#issuecomment-1858205343)
To make release notes more accurate we should update the features changes to exclude this
=> Don't manage members bugfix has a regression

.changes/unreleased/Feature-20231215-141513.yaml, opslevel/common.go, opslevel/datasource_opslevel_service.go
https://github.com/OpsLevel/terraform-provider-opslevel/issues/141
A service with 2 repositories.
```
$ cat main.tf
data "opslevel_service" "fetched_service" {
alias = "XXX"
}
output "fetched_repositories" {
value = data.opslevel_service.fetched_service.repositories
}
$ terraform apply
+ fetched_repositories = [
+ "Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRsYWIvMjQ4NzA",
+ "Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRodWIvOTY3",
]
```
A service with no repositories:
```
+ fetched_repositories = []
```
=> Add a list of repository ID's to the service datasource

.changes/unreleased/Feature-20231215-164432.yaml, opslevel/common.go, opslevel/datasource_opslevel_team.go
https://github.com/OpsLevel/terraform-provider-opslevel/issues/143
```
$ cat main.tf
data "opslevel_team" "fetched_team" {
alias = "platform"
}
output "fetched_memberships" {
value = data.opslevel_team.fetched_team.members
}
$ terraform plan
+ fetched_memberships = [
+ {
+ email = "person1@opslevel.com"
+ role  = "contributor"
},
+ {
+ email = "person2@opslevel.com"
+ role  = "contributor"
},
]
```
=> Add a list of team memberships to the service datasource

.changes/unreleased/Bugfix-20231219-101147.yaml, opslevel/resource_opslevel_team.go
This is a customer reported bug. A customer noticed that the `parent` on a team could be unset or could be changed unexpectedly. The customer reported [this on version 0.8.13.] (https://registry.terraform.io/providers/OpsLevel/opslevel/0.8.13/docs)
The customer noted that this happens when updating members, but that is coincidental. It can happen when updating anything about a team. 
The cause is a `d.Get()` value being used in the read a Team resource function, which is a clear typo. Also, a `d.HasChange()` call which can result in `input.Parent = nil` being sent in the team update input.
https://github.com/OpsLevel/team-platform/issues/156
Create a team with a parent. Works fine.
```
$ task apply 
+ resource "opslevel_team" "bugfixteam" {
+ aliases      = [
+ "bft",
]
+ id           = …
```
=> Bugfix for when a Team's parent is unset or changed unexpectedly

Taskfile.yml
Added tophatting commands `task hard-apply`, `hard-destroy`, `hard-plan` which will rebuild the Terraform provider every time and also auto approve. 
Tested locally, it works.
=> Add tophatting commands to Taskfile

.changes/unreleased/Bugfix-20240124-103647.yaml, opslevel/resource_opslevel_property_assignment.go
…t id
Fix updates to `owner` and `description` fields of Property Assignment resources. Before only ids were accepted even if an alias was provided.
=> fix updates to owner and description fields, can assign alias not just id

CONTRIBUTING.md, Taskfile.yml
1. Update `CONTRIBUTING.md` to reflect recent updates to `task` commands in `Taskfile.yml`
2. Remove `task hard-apply`, `task hard-destroy`, and `task hard-plan`.
3. Update `task apply`, `task destroy`, and `task plan` do what `task hard-*` did.
- Originally `task *` like were simple wrappers around `terraform *`. `task apply` was `terraform apply` in the "workspace" directory.
- Now, `task apply` and `task destroy` also have `-auto-approve` - as well as rebuilding the Go code every time.
=> update CONTRIBUTING and terraform tasks in Taskfile

.github/workflows/release.yml, .goreleaser.yml, Taskfile.yml
[Unify Version output across all tools and libraries](https://github.com/OpsLevel/team-platform/issues/213)
Somehow updating the version with the usual Go build flag `-X opslevel.version={{.Version}}` is not work. [{{.Version}} is legit](https://goreleaser.com/customization/templates/#common-fields). This is taking a page out of `opslevel-go`'s release book.
release it
=> update version during release workflow

opslevel/resource_opslevel_check_custom_event.go, opslevel/resource_opslevel_check_has_recent_deploy.go, opslevel/resource_opslevel_check_service_ownership.go, opslevel/resource_opslevel_integration_aws.go, opslevel/resource_opslevel_scorecard.go, opslevel/resource_opslevel_trigger_definition.go, opslevel/schema_checks.go
From `opslevel-go`, `Bool()` was removed with `RefOf` replacing it
=> replace dropped Bool func with RefOf func

.changes/unreleased/Feature-20240301-123335.yaml, opslevel/datasource_opslevel_property_definition.go, opslevel/datasource_opslevel_property_definitions.go, opslevel/resource_opslevel_property_assignment.go, opslevel/resource_opslevel_property_definition.go
https://github.com/OpsLevel/terraform-provider-opslevel/issues/203
https://github.com/OpsLevel/opslevel-go/pull/378
(tophatted during demo, here's what I used)
```
data "opslevel_team" "team_platform" {
alias = "platform"
}
data "opslevel_service" "proxysql" {
alias = "proxysql_new"
}
resource "opslevel_property_definition" "is_ready" {
allowed_in_config_files = true
name = "Is Ready for Demo"
description = "is this service ready for demo?"
schema = jsonencode({ "enum": ["not_ready", "almost_ready", "fully_ready", "not_applicable"], "type": "string" })
property_display_status = "visible"
}
resource "opslevel_property_assignment" "proxysql_readiness" {
definition = opslevel_property_definition.is_ready.id
owner = data.opslevel_service.proxysql.id
value = jsonencode("almost_ready")
}
output …
```
=> Add support for locked property assignments and allowed_in_config_files property definitions

Taskfile.yml
* Don't use `-fix` since it's experimental and it's better for devs to manually resolve this.
* Use `-include-pkgs` to greatly speed up CI.
=> fix nilaway in taskfile

opslevel/datasource_opslevel_property_definition.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_property_definition.tftest.hcl, tests/mock_datasource/property_definition.tfmock.hcl
Changes:
- Add `property_definition` datasource with tests.
```terraform
data "opslevel_property_definition" "pd1" {
identifier = "is_beta_feature"
}
output "pd_schema" {
value = data.opslevel_property_definition.pd1
}
```
```terraform
data.opslevel_property_definition.pd1: Reading...
data.opslevel_property_definition.pd1: Read complete after 0s [id=Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi85OA]
+ pd_schema = {
+ allowed_in_config_files = true
+ description             = ""
+ id                      = "Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi85OA"
+ identifier              = "is_beta_feature"
+ name                    = "Is Beta Feature"
+ …
```
=> add property_definition datasource, with tests

opslevel/datasource_opslevel_rubric_level.go, opslevel/datasource_opslevel_tier.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_rubric_level.tftest.hcl, tests/datasource_tier.tftest.hcl, tests/mock_datasource/rubric_level.tfmock.hcl, tests/mock_datasource/tier.tfmock.hcl
Changes:
- Add `rubric_level` datasource with tests.
```terraform
data "opslevel_rubric_level" "good" {
filter {
field = "alias"
value = "good"
}
}
data "opslevel_rubric_level" "second" {
filter {
field = "index"
value = 2
}
}
data "opslevel_rubric_level" "amazing" {
filter {
field = "id"
value = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvODgz"
}
}
data "opslevel_rubric_level" "ultimate" {
filter {
field = "name"
value = "Ultimate"
}
}
output "amazing" {
value = data.opslevel_rubric_level.amazing
}
output "second" {
value = data.opslevel_rubric_level.second
}
output "good" {
value = data.opslevel_rubric_level.good
}
output "ultimate" {
value = data.opslevel_rubric_level.ultimate
}
```
```terraform …
```
=> add rubric_level datasource, with tests

opslevel/datasource_opslevel_scorecard.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_scorecard.tftest.hcl, tests/mock_datasource/scorecard.tfmock.hcl
Changes:
- Add `scorecard` datasource with tests.
```terraform
data "opslevel_scorecard" "fancy" {
identifier = "fancy_scorecard"
}
data "opslevel_scorecard" "test" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzYwNw"
}
output "fancy" {
value = data.opslevel_scorecard.fancy
}
output "test" {
value = data.opslevel_scorecard.test
}
```
```terraform
data.opslevel_scorecard.test: Reading...
data.opslevel_scorecard.fancy: Reading...
data.opslevel_scorecard.fancy: Read complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzgxMA]
data.opslevel_scorecard.test: Read complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzYwNw]
+ fancy = {
+ affects_overall_service_levels = false
+ aliases …
```
=> add scorecard datasource, with tests

.changes/unreleased/Feature-20240321-141316.yaml, opslevel/provider.go
```tf
data "opslevel_webhook_action" "example" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8zNjg"
}
output "example" {
value = data.opslevel_webhook_action.example
}
```
```tf
data.opslevel_webhook_action.example: Reading...
data.opslevel_webhook_action.example: Read complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8zNjg]
+ example = {
+ description = "Pages the On Call"
+ headers     = {
+ accept        = "application/vnd.pagerduty+json;version=2"
+ authorization = "Token token=XXXXXXXXXXXXXX"
+ content-type  = "application/json"
+ from          = "john@opslevel.com"
}
+ id          = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8zNjg"
+ identifier  = …
```
=> release webhook_actions datasource

.changes/unreleased/Feature-20240322-131940.yaml, opslevel/datasource_opslevel_user.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_user.tftest.hcl, tests/mock_datasource/user.tfmock.hcl
Changes:
- Add `user` datasource with tests.
```terraform
data "opslevel_user" "user" {
identifier = "david+orange@opslevel.com"
}
output "user" {
value = data.opslevel_user.user
}
```
```terraform
data.opslevel_user.user: Reading...
data.opslevel_user.user: Read complete after 0s [id=Z2lk...]
+ user = {
+ email      = "david+orange@opslevel.com"
+ id         = "Z2lk...."
+ identifier = "david+orange@opslevel.com"
+ name       = "David"
+ role       = "admin"
}
You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```
=> add user datasource, with tests

opslevel/datasource_opslevel_webhook_action.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_webhook_action.tftest.hcl, tests/mock_datasource/webhook_action.tfmock.hcl
Changes:
- Add `webhook_action` datasource with tests.
```terraform
data "opslevel_webhook_action" "example" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8zNjk"
}
output "webhook_action" {
value = data.opslevel_webhook_action.example
}
```
```terraform
data.opslevel_webhook_action.example: Reading...
data.opslevel_webhook_action.example: Read complete after 0s [name=Page The On Call]
+ webhook_action = {
+ description = "Pages the On Call"
+ headers     = {
+ accept        = "application/vnd.pagerduty+json;version=2"
+ authorization = "Token token=XXXXXXXXXXXXXX"
+ content-type  = "application/json"
+ from          = "john@opslevel.com"
}
+ identifier …
```
=> add webhook_action datasource, with tests

opslevel/provider.go, opslevel/resource_opslevel_domain.go, opslevel/resource_opslevel_user.go, tests/mock_resource/user.tfmock.hcl, tests/resource_user.tftest.hcl, tests/resources.tf
Changes:
- Add `user` resource, with tests
```terraform
resource "opslevel_user" "foo" {
name  = "Foo Bar"
email = "foo_bar@baz.com"
role  = "user"
}
```
Create user. Run `terraform apply`
```terraform
+ create
+ resource "opslevel_user" "foo" {
+ email        = "foo_bar@baz.com"
+ name         = "Foo Bar"
+ role         = "user"
}
Do you want to perform these actions?
Terraform will perform the actions described above. …
```
=> add user resource, with tests

opslevel/resource_opslevel_domain.go
- Domain field in `opslevel-go` updated from `Aliases` to `ManagedAliases`
- `Read` operation uses `NewDomainResourceModel(ctx, *resource)` just like `Create` and `Update`.
- Setting `LastUpdated` field done outside of `NewDomainResourceModel()`. 
Using this config:
```tf
resource "opslevel_domain" "example" {
name        = "FANCY FEAST"
description = "CATS FEAST ON FANCY TABLES"
owner       = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5"
note        = "CATS LOVE FANCY TABLES"
}
```
Create domain, `terraform apply`
```tf
+ create
+ resource "opslevel_domain" …
```
=> update opslevel domain aliases field, fix read function

opslevel/common.go, opslevel/provider.go, opslevel/resource_opslevel_domain.go, opslevel/resource_opslevel_secrets.go, opslevel/resource_opslevel_user.go, tests/mock_resource/secret.tfmock.hcl, tests/resource_secret.tftest.hcl, tests/resources.tf
Changes:
- Add `secret` resource, with tests
- Update `timeLastUpdated()` to return new type
```terraform
resource "opslevel_secret" "my_secret" {
alias = "secret-alias-123456"
owner = "platform"
value = "too_many_passwords_123"
}
```
Create secret. Run `terraform apply`
```terraform
+ create
+ resource "opslevel_secret" "my_secret" {
+ alias        = "secret-alias-123456"
+ created_at   = (known after apply)
+ owner        = "platform"
+ updated_at   = (known after …
```
=> add secret resource, with tests, update timeLastUpdated

Taskfile.yml
Add `task reapply`. This is like `task apply` but keeps terraform state which is needed during tophatting.
=> add task reapply, runs task apply but keeps local terraform state

Taskfile.yml
Keep Terraform state in `task plan`, `task apply`, `task destroy`. We need terraform state during tophatting to see how the terraform state is changed and do not want it deleted.
Remove `task reapply` - this was a temporary workaround.
=> keep terraform state in routine terraform task commands

opslevel/datasource_opslevel_lifecycle.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_lifecycle.tftest.hcl, tests/mock_datasource/lifecycle.tfmock.hcl
```
data "opslevel_lifecycle" "l1" {
filter {
field = "alias"
value = "generally_available"
}
}
data "opslevel_lifecycle" "l2" {
filter {
field = "id"
value = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
}
}
output "o1" {
value = data.opslevel_lifecycle.l1
}
output "o2" {
value = data.opslevel_lifecycle.l2
}
```
```
+ o1 = {
+ alias       = "generally_available"
+ description = "Service is supporting features available to be used by all customers, and should be fully stable."
+ filter      = {
+ field = "alias"
+ value = "generally_available"
}
+ id          = "Z2lkOi8vb3BzbGV2ZWwvTGlmZWN5Y2xlLzQ"
+ index       = 4
+ name        = "Generally Available"
}
+ o2 = {
+ alias       = "generally_available"
+ description = …
```
=> add lifecycle datasource

opslevel/datasource_opslevel_service.go, tests/data_sources.tf, tests/datasource_service.tftest.hcl
Changes:
- Update `service` datasource and tests. Replaced `identifier` input with `id` or `alias` to match [public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/data-sources/service)
```terraform
data "opslevel_service" "platform_repo_alias" {
alias = "platform.repo"
}
data "opslevel_service" "test" {
id = "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS81Njg3Ng"
}
output "platform_repo_alias" {
value = data.opslevel_service.platform_repo_alias
}
output "test" {
value = data.opslevel_service.test
}
```
```terraform
data.opslevel_service.test: Reading...
data.opslevel_service.platform_repo_alias: Reading...
data.opslevel_service.platform_repo_alias: Read complete after 1s …
```
=> replace identifier with id or alias for service datasource

opslevel/datasource_opslevel_team.go, opslevel/provider.go, tests/data_sources.tf, tests/datasource_team.tftest.hcl, tests/mock_datasource/team.tfmock.hcl
Current docs for team: https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/data-sources/team
```
data "opslevel_team" "engineering" {
alias = "engineering"
}
data "opslevel_team" "platform" {
id = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNjc4"
}
output "o1" {
value = data.opslevel_team.engineering
}
output "o2" {
value = data.opslevel_team.platform
}
```
```
+ o1 = {
+ alias        = "engineering"
+ id           = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMDI0Mg"
+ members      = [
+ {
+ email = "x@opslevel.com"
+ role  = "manager"
},
]
+ name         = "Engineering"
+ parent_alias = "product"
+ parent_id    = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMDI0Mw"
}
+ o2 = {
+ alias        = "platform"
+ id           = …
```
=> add team datasource

opslevel/resource_opslevel_domain.go, opslevel/resource_opslevel_secrets.go, opslevel/resource_opslevel_user.go
Add missing `stringplanmodifier.RequiresReplace()` to `secret` and `user` resources. I missed this during my first pass at these resource upgrade.
The old `ForceNew: true,` from SDKv2 needs to be replaced by a `RequiresReplace` PlanModifier [see upgrade docs](https://developer.hashicorp.com/terraform/plugin/framework/migrating/attributes-blocks/force-new) and [RequiresReplace doc](https://developer.hashicorp.com/terraform/plugin/framework/resources/plan-modification#requiresreplace)
- [link to secret's email field](https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/opslevel/resource_opslevel_user.go#L34) with `ForceNew: true,`
- [link to user's alias field](https://github.com/OpsLevel/terraform-provider-opslevel/blob/main/opslevel/resource_opslevel_secrets.go#L29) with …
=> add missing plan modifiers to secret and user resources

opslevel/provider.go, opslevel/resource_opslevel_infra.go, opslevel/terraform_type_conversions.go, opslevel/validators.go, tests/data_sources.tf, tests/mock_resource/infra.tfmock.hcl, tests/resource_infra.tftest.hcl, tests/resources.tf, tests/variables.tf
[public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/infrastructure)
Changes:
- Add `infrastructure` resource, with tests
```terraform
resource "opslevel_infrastructure" "big" {
aliases = ["one", "two"]
name                = "big-query-123"
external_id         = "example_2_1234"
zone                = "us-east-1"
engine              = "bigquery"
engine_version      = "1.28.0"
endpoint            = "https://console.cloud.google.com/..."
replica             = false
publicly_accessible = false
storage_size = {
unit  = "GB"
value = 700
}
storage_type = "gp3"
storage_iops = {
unit  = "per second"
value = 12000
}
})
owner = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5" …
```
=> add infra resource, with tests

opslevel/provider.go, opslevel/resource_opslevel_rubric_level.go, opslevel/terraform_type_conversions.go, tests/mock_resource/rubric_level.tfmock.hcl, tests/resource_rubric_level.tftest.hcl, tests/resources.tf
[public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/rubric_level)
Changes:
- Add `rubric_level` resource, with tests
```tf
resource "opslevel_rubric_level" "mystery" {
name        = "mystery"
description = "mystery level"
}
resource "opslevel_rubric_level" "five" {
name        = "five"
description = "five level"
index       = 5
}
```
```tf
+ create
+ resource "opslevel_rubric_level" "five" {
+ description  = "five level"
+ index        = 5
+ …
```
=> add rubric_level resource, with tests

opslevel/resource_opslevel_infra.go
```tf
resource "opslevel_infrastructure" "big" {
aliases = ["one", "two"]
name                = "big-query-123"
external_id         = "example_2_1234"
zone                = "us-east-1"
engine              = "bigquery"
engine_version      = "1.28.0"
endpoint            = "https://console.cloud.google.com/..."
replica             = false
publicly_accessible = false
storage_size = {
unit  = "GB"
value = 700
}
storage_type = "gp3"
storage_iops = {
unit  = "per second"
value = 12000
}
})
owner = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS85NzU5"
provider_data = {
account = "dev"
name    = "google cloud"
type    = "BigQuery"
url     = "https://console.cloud.google.com/..."
}
schema = "Database"
}
```
```tf
Terraform used the selected providers to generate the following execution plan. …
```
=> fix infra resource alias create,update

opslevel/common.go, opslevel/provider.go, opslevel/resource_opslevel_trigger_definition.go, opslevel/terraform_type_conversions.go, tests/mock_resource/trigger_definition.tfmock.hcl, tests/resource_trigger_definition.tftest.hcl, tests/resources.tf
[trigger_definiton public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/trigger_definiton)
Changes:
- Add `trigger_definiton` resource, with tests
```tf
resource "opslevel_trigger_definition" "example" {
access_control           = "everyone"
action                   = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi8zNjg"
description              = "pages the on call"
entity_type              = "SERVICE"
extended_team_access     = ["shopping_cart_2", "shopping_cart"]
filter                   = "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzgwMg"
manual_inputs_definition = <<EOT
---
version: 1
inputs:
- identifier: IncidentTitle
displayName: Title
description: Title of the incident to trigger
type: …
```
=> Add Trigger Definiton, with tests

opslevel/provider.go, opslevel/resource_opslevel_domain.go, opslevel/resource_opslevel_filter.go, opslevel/resource_opslevel_rubric_category.go, opslevel/resource_opslevel_rubric_level.go, opslevel/resource_opslevel_service.go, opslevel/resource_opslevel_team.go, opslevel/resource_opslevel_user.go, tests/mock_resource/team.tfmock.hcl, tests/resource_team.tftest.hcl, tests/resources.tf
```
resource "opslevel_team" "team_parent" {
aliases          = sort(["parent_team"])
name             = "The Parent Team II"
responsibilities = "Just a parent team, hello world"
member {
email = "kyle+pat@opslevel.com"
role  = "manager"
}
}
resource "opslevel_team" "team_1" {
aliases          = sort(["platform3", "team_platform3", "team_platform_the_third", "child_team"])
name             = "Team Platform 3"
responsibilities = "Team Platform the third (3)"
member {
email = "david+pat@opslevel.com"
role  = "manager"
}
member {
email = "kyle+pat@opslevel.com"
role  = "manager"
}
member {
email = "taimoor+pat@opslevel.com"
role  = "contributor"
}
parent = opslevel_team.team_parent.id
}
resource "opslevel_team" "team_empty" {
name = "Empty …
```
=> Add resource team (works)

opslevel/provider.go, opslevel/resource_opslevel_repository.go, opslevel/resource_opslevel_service.go, tests/mock_resource/repository.tfmock.hcl, tests/resource_repository.tftest.hcl, tests/resources.tf
[repository public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/repository)
Changes:
- Add `repository` resource, with tests
```tf
resource "opslevel_repository" "repo_with_alias" {
identifier = "github.com:suraj-testing2/Shoes_Soda"
owner      = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8yMjU"
}
resource "opslevel_repository" "repo_with_id" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvUmVwb3NpdG9yaWVzOjpHaXRodWIvNDYzMw"
owner      = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8yMjU"
}
```
```tf
+ create
+ resource "opslevel_repository" "repo_with_alias" …
```
=> add repository resource, with tests

opslevel/provider.go, opslevel/resource_opslevel_system.go, tests/mock_resource/system.tfmock.hcl, tests/resource_system.tftest.hcl, tests/resources.tf
[system public docs](https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/system)
Changes:
- Add `system` resource, with tests
```tf
resource "opslevel_system" "example" {
name = "Sound system 2"
}
```
```tf
+ create
+ resource "opslevel_system" "example" {
+ aliases      = (known after apply)
+ name         = "Sound system 2"
}
opslevel_system.example: Creating...
opslevel_system.example: Creation complete after …
```
=> add system resource, with tests

examples/data-sources/opslevel_property_definition/data-source.tf, examples/resources/opslevel_property_definition/resource.tf, opslevel/provider.go, opslevel/resource_opslevel_property_definition.go, opslevel/validators.go, tests/resource_property_definition.tftest.hcl, tests/resources.tf
https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/property_definition
```
opslevel_property_definition.color_picker: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to opslevel_property_definition.color_picker, provider "provider[\"registry.terraform.io/opslevel/opslevel\"]" produced an unexpected new value: .property_display_status: was null, but now cty.StringVal("visible").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
task: Failed to run task "terraform-apply": exit status 1
```
``` …
```
=> Add new property definition resource

opslevel/provider.go, opslevel/resource_opslevel_check_has_documentation.go, tests/resource_check_has_documentation.tftest.hcl, tests/resources.tf
Add has documentation check
Create
```tf
resource "opslevel_check_has_documentation" "example" {
name       = "foo"
category   = data.opslevel_rubric_category.security.id
level      = data.opslevel_rubric_level.bronze.id
document_subtype = "openapi"
document_type = "api"
}
```
```bash
+ resource "opslevel_check_has_documentation" "example" {
+ category         = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description      = (known after apply)
+ document_subtype = "openapi"
+ document_type    = "api"
+ enabled          = false
+ id               = (known after apply)
+ last_updated     = (known after apply)
+ level            = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name             = "foo"
}
```
Update
```tf
resource "opslevel_check_has_documentation" "example" {
name       = "foo"
category …
```
=> Add has documentation check

opslevel/provider.go, opslevel/resource_opslevel_check_repository_grep.go, tests/resource_check_repository_grep.tftest.hcl, tests/resources.tf
Add repo grep check
Create
```
+ resource "opslevel_check_repository_grep" "example" {
+ category                = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description             = (known after apply)
+ directory_search        = false
+ enabled                 = true
+ file_contents_predicate = {
+ value = "**/hello.go"
}
+ filepaths               = [
+ "/src",
+ "/tests",
]
+ id                      = (known after apply)
+ last_updated            = (known after apply)
+ level                   = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name                    = "foo"
}
```
Create - no predicate FAILS because of a bug in opslevel-go
```bash
│ Unable to create check_repository_grep, got error: Message: Variable $input of type CheckRepositoryGrepCreateInput! was provided …
```
=> Add repo grep check

examples/resources/opslevel_check_repository_file/resource.tf, opslevel/provider.go, opslevel/resource_opslevel_check_repository_file.go, tests/resource_check_repository_file.tftest.hcl, tests/resources.tf
Add repo file check
Create
```bash
+ resource "opslevel_check_repository_file" "example" {
+ category          = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description       = (known after apply)
+ directory_search  = false
+ enabled           = false
+ filepaths         = [
+ "main.go",
]
+ id                = (known after apply)
+ last_updated      = (known after apply)
+ level             = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name              = "foo"
+ use_absolute_root = true
}
```
Update Add Predicate
```bash
~ resource "opslevel_check_repository_file" "example" {
+ file_contents_predicate = {
+ value = "foo"
}
id                      = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpSZXBvRmlsZS8yNDE2Mg"
+ last_updated            = (known after apply)
name                    = …
```
=> add check repo file

opslevel/provider.go, opslevel/resource_opslevel_check_alert_source_usage.go, tests/resource_check_alert_source_usage.tftest.hcl, tests/resources.tf
Add alert source usage check
Create
```bash
+ resource "opslevel_check_alert_source_usage" "example" {
+ alert_name_predicate = {
+ value = "dev"
}
+ alert_type           = "pagerduty"
+ category             = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description          = (known after apply)
+ enabled              = false
+ id                   = (known after apply)
+ last_updated         = (known after apply)
+ level                = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name                 = "foo"
}
```
Update able to null out predicate
```bash
~ resource "opslevel_check_alert_source_usage" "example" {
- alert_name_predicate = {
- type  = "contains" -> null
- value = "dev" -> null
} -> null
+ description          = (known after apply)
id                   = …
```
=> Add alert source usage check

examples/resources/opslevel_check_repository_search/resource.tf, opslevel/provider.go, opslevel/resource_opslevel_check_repository_search.go, tests/resource_repository_search.tftest.hcl, tests/resources.tf
Add repo search check
Create
```bash
+ resource "opslevel_check_repository_search" "example" {
+ category                = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description             = (known after apply)
+ enabled                 = true
+ file_contents_predicate = {
+ value = "postgres"
}
+ file_extensions         = [
+ "sbt",
+ "py",
]
+ id                      = (known after apply)
+ last_updated            = (known after apply)
+ level                   = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name                    = "foo"
}
```
Update file_extensions
```bash
~ resource "opslevel_check_repository_search" "example" {
~ description             = "Repo contains search term 'postgres' in at least one .sbt, .py, or .go file." -> (known after apply)
~ …
```
=> add repo search check

opslevel/provider.go, opslevel/resource_opslevel_check_service_ownership.go, tests/resource_check_service_ownership.tftest.hcl, tests/resources.tf
Add service ownership check
There is one bug with this and its due to a bug in the API not in our tools
Create
```bash
+ resource "opslevel_check_service_ownership" "example" {
+ category               = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ contact_method         = "ANY"
+ description            = (known after apply)
+ enabled                = true
+ id                     = (known after apply)
+ last_updated           = (known after apply)
+ level                  = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name                   = "foo"
+ notes                  = "Optional additional info on why this check is run or how to fix it"
+ require_contact_method = true
+ tag_key                = "team"
+ tag_predicate          = {
+ type  = "equals"
+ value = "frontend"
}
}
```
Update tag …
=> add service ownership check

opslevel/provider.go, opslevel/resource_opslevel_check_tag_defined.go, tests/resource_check_tag_defined.tftest.hcl, tests/resources.tf
Add tag defined check
Create
```bash
+ resource "opslevel_check_tag_defined" "example" {
+ category      = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description   = (known after apply)
+ enabled       = true
+ id            = (known after apply)
+ last_updated  = (known after apply)
+ level         = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name          = "foo"
+ tag_key       = "environment"
+ tag_predicate = {
+ value = "dev"
}
}
```
Create without predicate
```bash
+ resource "opslevel_check_tag_defined" "example" {
+ name         = …
```
=> add tag defined check

opslevel/provider.go, opslevel/resource_opslevel_check_tool_usage.go, tests/resources.tf, tests/resources_check_tool_usage.tftest.hcl
Add tool usage check
create - no predicates
```bash
+ resource "opslevel_check_tool_usage" "example" {
+ category      = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description   = (known after apply)
+ enabled       = true
+ id            = (known after apply)
+ last_updated  = (known after apply)
+ level         = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name          = "foo"
+ tool_category = "metrics"
}
```
create - name predicate
```bash
+ resource "opslevel_check_tool_usage" "example" {
+ category            = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description         = (known after apply)
+ enabled             = true
+ id                  = (known after apply)
+ last_updated        = (known after apply)
+ level               = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ name                = …
```
=> Add tool usage check

opslevel/provider.go, opslevel/resource_opslevel_check_custom_event.go, tests/resource_check_custom_event.tftest.hcl, tests/resources.tf
Add Custom Event Check
Create
```bash
+ resource "opslevel_check_custom_event" "example" {
+ category          = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTY1"
+ description       = (known after apply)
+ enabled           = true
+ id                = (known after apply)
+ integration       = "Z2lkOi8vb3BzbGV2ZWwvSW50ZWdyYXRpb25zOjpFdmVudHM6OkdlbmVyaWNJbnRlZ3JhdGlvbi81Mzkw"
+ last_updated      = (known after apply)
+ level             = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvNTIw"
+ message           = <<-EOT
{% if check.passed %}
{% else %}
service **{{ data.messages[ctx.index].incident.service.id }}** has an unresolved incident.
{% endif %}
OpsLevel note: here you can fill in more details about this check. You can even include `data` from the payload, `params` specified in the URL and context `ctx` such …
```
=> add custom event check

opslevel/provider.go, opslevel/resource_opslevel_check_service_property.go, tests/resource_check_service_property.tftest.hcl, tests/resources.tf
Add service property check
Create - without predicate
```bash
+ resource "opslevel_check_service_property" "example" {
+ property     = "language"
}
```
update - add predicate
```bash
~ resource "opslevel_check_service_property" "example" {
~ description  = "The service has a language." -> (known after apply)
id           = "Z2lkOi8vb3BzbGV2ZWwvQ2hlY2tzOjpTZXJ2aWNlUHJvcGVydHkvMjQxNzk"
+ predicate    = {
+ type = "exists"
}
}
```
update - remove predicate
```
~ resource …
```
=> Add service property check

opslevel/provider.go, opslevel/resource_opslevel_property_assignment.go, tests/mock_resource/property_assignment.tfmock.hcl, tests/mock_resource/property_definition.tfmock.hcl, tests/resource_property_assignment.tftest.hcl, tests/resources.tf
https://registry.terraform.io/providers/OpsLevel/opslevel/latest/docs/resources/property_assignment
Config:
```
resource "opslevel_property_definition" "container" {
name                    = "Container"
allowed_in_config_files = true
property_display_status = "visible"
schema = jsonencode({
"type" : "object",
"properties" : {
"container_id" : {
"type" : "string",
"format" : "uuid"
},
"build_date" : {
"type" : "string",
"format" : "date-time"
},
"container_name" : {
"type" : "string",
"pattern" : "^gcr.io/[a-z]+"
}
},
"required" : [
"container_id",
"container_name"
]
})
}
resource "opslevel_property_assignment" "container" {
owner      = "sample_shopping_cart_service"
definition = opslevel_property_definition.container.id
value      = …
```
=> add new property assignment resource

opslevel/provider.go, opslevel/resource_opslevel_tag.go, tests/resource_tag.tftest.hcl, tests/resources.tf
Add tag resource
Create
```bash
+ resource "opslevel_tag" "example" {
+ id                  = (known after apply)
+ key                 = "foo"
+ last_updated        = (known after apply)
+ resource_identifier = "terraform-service"
+ resource_type       = "Service"
+ value               = "bar"
}
```
Delete / Create
```
-/+ resource "opslevel_tag" "example" {
~ id                  = "Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNzg4MDIy" -> (known after apply)
+ last_updated        = (known after apply)
~ value               = "bar" -> "billy" # forces replacement
}
```
Delete / Create - Domain
```
-/+ resource "opslevel_tag" "example" {
~ id                  = "Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNzg4MDY0" -> (known after apply)
+ last_updated        = (known after apply)
~ resource_identifier = "testing" -> …
```
=> Add tag resource

.changes/unreleased/Feature-20240417-110524.yaml, opslevel/datasource_opslevel_rubric_categories.go, opslevel/datasource_opslevel_rubric_category.go, opslevel/provider.go, tests/mock_datasource/rubric_category.tfmock.hcl
Changes:
- Add `rubric_categories` datasource
```terraform
data "opslevel_rubric_categories" "all" {}
output "found_all" {
value = data.opslevel_rubric_categories.all
}
```
```terraform
data.opslevel_rubric_categories.all: Reading...
data.opslevel_rubric_categories.all: Read complete after 0s
+ found_all = {
+ rubric_categories = [
+ {
+ id   = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNDIx"
+ name = "Security"
},
+ {
+ id   = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNDIy"
+ name = "Reliability"
},
+ {
+ id   = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNDIz"
+ name = "Performance"
},
+ {
+ id   = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNDI0"
+ name = "Scalability"
},
+ {
+ id   = …
```
=> add rubric_categories datasource

opslevel/resource_opslevel_service.go
Acknowledge known issue raised by customer
```tf
resource "opslevel_service" "test" {
aliases                       = ["one-test-one", "TWO-TEST-TW2O", "two-test-two"]
api_document_path             = "my/path/doc.yaml"
description                   = "fancy things"
framework                     = "da-best"
language                      = "go"
lifecycle_alias = "alpha"
name            = "tophatting-service"
owner                         = "platform"
preferred_api_document_source = "PUSH"
product                       = "tophat"
tags                          = ["key:value"]
tier_alias                    = "tier_2"
}
```
```tf
opslevel_service.test: Refreshing state... [id=Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS8xMjAxNTE]
Terraform used the selected providers to generate the following execution plan. …
```
=> add known error to service update

.changes/unreleased/Feature-20240423-132752.yaml, opslevel/datasource_opslevel_repositories_all.go, opslevel/datasource_opslevel_services.go, opslevel/datasource_opslevel_services_all.go, opslevel/provider.go
Changes:
- Add `services` datasource
```terraform
data "opslevel_services" "all" {}
data "opslevel_services" "by_framework" {
filter = {
field = "framework"
value = "terraform"
}
}
data "opslevel_services" "by_language" {
filter = {
field = "language"
value = "Go"
}
}
data "opslevel_services" "by_lifecycle" {
filter = {
field = "lifecycle"
value = "alpha"
}
}
data "opslevel_services" "by_owner" {
filter = {
field = "owner"
value = "frontend"
}
}
data "opslevel_services" "by_product" {
filter = {
field = "product"
value = "OSS"
}
}
data "opslevel_services" "by_tag" {
filter = {
field = "tag"
value = "environment:dev"
}
}
data "opslevel_services" "by_tier" {
filter = {
field = "tier"
value = "tier_4"
}
}
output "all" { …
```
=> add services datasource back in

.changes/unreleased/Feature-20240425-160915.yaml, opslevel/datasource_opslevel_services_all.go
[Support the filterIdentifier argument in the services datasource in terraform ](https://github.com/OpsLevel/team-platform/issues/321)
Relies on [upstream PR being merged](https://github.com/OpsLevel/opslevel-go/pull/391)
```tf
data "opslevel_filter" "test_filter" {
filter {
field = "name"
value = "JS Services"
}
}
data "opslevel_services" "by_filter_id" {
filter = {
field = "filter"
value = data.opslevel_filter.test_filter.id
}
}
output "by_framework" {
value = data.opslevel_services.by_filter_id
}
```
```tf
data.opslevel_filter.test_filter: Reading...
data.opslevel_filter.test_filter: Read complete after 0s [id=Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzEwNTM]
data.opslevel_services.by_filter_id: Reading...
data.opslevel_services.by_filter_id: Read complete after 1s
+ …
```
=> can filter services datasource by filter id

.changes/unreleased/Bugfix-20240506-165314.yaml, opslevel/resource_opslevel_service.go, opslevel/terraform_type_conversions.go
https://github.com/OpsLevel/team-platform/issues/356
```
resource "opslevel_service" "mon_service" {
description = "hello world"
framework = "rails"
language = "ruby"
lifecycle_alias = "pre-alpha"
name = "mon_service"
owner = "team_platform_3"
tier_alias = "tier_4"
}
```
```
+ create
+ resource "opslevel_service" "mon_service" {
+ name         = "mon_service"
}
opslevel_service.mon_service: Creating...
opslevel_service.mon_service: Creation complete after 1s …
```
=> fix `'' was not found` for resource opslevel_service on `lifecycle_alias`, `tier_alias`

Taskfile.yml, examples/data-sources/opslevel_domains/data-source.tf, examples/data-sources/opslevel_filters/data-source.tf, examples/data-sources/opslevel_integrations/data-source.tf, examples/data-sources/opslevel_lifecycles/data-source.tf, examples/data-sources/opslevel_property_definitions/data-source.tf, examples/data-sources/opslevel_repositories/data-source.tf, examples/data-sources/opslevel_rubric_categories/data-source.tf, examples/data-sources/opslevel_rubric_levels/data-source.tf, examples/data-sources/opslevel_scorecards/data-source.tf, examples/data-sources/opslevel_services/data-source.tf, examples/data-sources/opslevel_systems/data-source.tf, examples/data-sources/opslevel_teams/data-source.tf, examples/data-sources/opslevel_tiers/data-source.tf, examples/data-sources/opslevel_user/data-source.tf, examples/data-sources/opslevel_users/data-source.tf, examples/data-sources/opslevel_webhook_action/data-source.tf, examples/data-sources/opslevel_webhook_actions/data-source.tf, examples/resources/opslevel_check_alert_source_usage/resource.tf, examples/resources/opslevel_check_custom_event/resource.tf, examples/resources/opslevel_check_manual/resource.tf, examples/resources/opslevel_check_repository_file/resource.tf, examples/resources/opslevel_check_service_property/resource.tf, examples/resources/opslevel_check_tool_usage/resource.tf, examples/resources/opslevel_service_tag/resource.tf, examples/resources/opslevel_team_tag/resource.tf, examples/resources/opslevel_trigger_definition/resource.tf
[Ensure the terraform registry docs generator still works](https://github.com/OpsLevel/team-platform/issues/349)
Update datasources and resources configs in `examples/` directory.
Updates like ` alert_name_predicate {` --> ` alert_name_predicate = {` are a result of updating blocks to SingleNestedAttributes and will need to be documented in the 1.0 release.
Added examples for:
- `opslevel_webhook_actions` datasource
- `opslevel_user`  datasource
- `opslevel_service_tag` resource
- `opslevel_team_tag` resource
`task docs`
=> update examples for docs, add some missing resource examples

.changes/unreleased/Bugfix-20240510-094522.yaml, opslevel/datasource_opslevel_services_all.go
[nil pointer deference on plural service datasource ](https://github.com/OpsLevel/terraform-provider-opslevel/issues/334)
Fix listing services, show empty list when no services exist.
```tf
data "opslevel_services" "all" {}
output "all_services" {
value = data.opslevel_services.all.services
}
```
```tf
data.opslevel_services.all: Reading...
data.opslevel_services.all: Read complete after 1s
+ all_services = []
You can apply this plan to save these new output values to the Terraform state, without changing any real infrastructure.
```
=> fix listing services, show empty list when no services exist

.github/workflows/tests-integration.yml
[Setup Integration Testing](https://github.com/OpsLevel/team-platform/issues/346)
Add manually triggered CI workflow that runs integration tests against the PAT account.
This runs `task test-integration` which:
- builds the latest Go code on `main`
- runs `terraform init`
- runs `test -var-file=test.tfvars -var="api_token=$OPSLEVEL_API_TOKEN"` from `tests/remote`
---
=> add manual test integration workflow to CI

.changes/unreleased/Refactor-20240530-145934.yaml, opslevel/resource_opslevel_infra.go, opslevel/resource_opslevel_service.go, opslevel/resource_opslevel_team.go, opslevel/terraform_type_conversions.go, tests/local/resource_infra.tftest.hcl, tests/local/resource_service.tftest.hcl, tests/local/resource_team.tftest.hcl
[aliases field has issues](https://github.com/OpsLevel/team-platform/issues/340)
Convert `aliases` field in `opslevel_infrastructure`, `opslevel_service`, and `opslevel_team` from list type to set.
This is a sensible solution to the unordered nature of aliases on return. 
```tf
resource "opslevel_infrastructure" "example" {
aliases = []
owner   = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzMg"
schema  = "Database"
name = "my-database"
})
}
resource "opslevel_service" "example" {
name    = "frosting-patrol1"
aliases = []
}
resource "opslevel_team" "example" {
name             = "bake-off2"
responsibilities = "Baking cakes"
aliases          = []
}
```
```tf
opslevel_team.example: Refreshing state... [id=Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xOTE2Mg]
opslevel_infrastructure.example: Refreshing …
```
=> convert aliases attribute from list to set

.changes/unreleased/Feature-20240531-112947.yaml, opslevel/resource_opslevel_check_alert_source_usage.go, opslevel/resource_opslevel_check_base.go, opslevel/resource_opslevel_check_repository_file.go, opslevel/resource_opslevel_check_repository_grep.go, opslevel/resource_opslevel_check_repository_search.go, opslevel/resource_opslevel_check_service_ownership.go, opslevel/resource_opslevel_check_service_property.go, opslevel/resource_opslevel_check_tag_defined.go, opslevel/resource_opslevel_check_tool_usage.go
[Add filter predicate validation for Terraform configs](https://github.com/OpsLevel/team-platform/issues/376)
Add predicate validation at config time, i.e. `terraform validate` (pre-plan).
NOTE: predicated on update in this [opslevel-go PR](https://github.com/OpsLevel/opslevel-go/pull/410) 
```tf
resource "opslevel_check_alert_source_usage" "example" {
name    = "foo"
enabled = true
category = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNjk3OQ"
level    = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvMzcwOA"
owner    = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
filter   = "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzQ3NDM"
notes    = "Optional additional info on why this check is run or how to fix it"
alert_type = "pagerduty" # one of: "pagerduty", "datadog", "opsgenie"
alert_name_predicate = {
type  = "exists"
value = null
}
} …
```
=> add Terraform config validation to filter predicates

.changes/unreleased/Bugfix-20240603-103816.yaml, opslevel/resource_opslevel_trigger_definition.go
Fix unwanted update to optional field `opslevel_ trigger_definition.entity_type` when not specified in Terraform config.
If `entity_type` is not specified in the Terraform config, default to what is returned by the API.
```tf
resource "opslevel_trigger_definition" "example" {
access_control = "everyone"
action         = "Z2lkOi8vb3BzbGV2ZWwvQ3VzdG9tQWN0aW9uczo6V2ViaG9va0FjdGlvbi81ODk"
name           = "Page The On Call"
owner          = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
published      = false
}
```
```tf
+ create
+ resource "opslevel_trigger_definition" "example" {
+ access_control = "everyone"
+ action …
```
=> fix unwanted update to trigger_definition.entity_type when specified

.changes/unreleased/Bugfix-20240606-135829.yaml, opslevel/resource_opslevel_team_tag.go
```tf
resource "opslevel_team_tag" "team_tag_1" {
key        = "key2"
value      = "value"
team       = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
team_alias = "team_platform_3_a"
}
```
```bash
terraform import opslevel_team_tag.team_tag_1 'Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA:Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNjU0OTMw'
```
outputs
```tf
opslevel_team_tag.team_tag_1: Importing from ID "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA:Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNjU0OTMw"...
opslevel_team_tag.team_tag_1: Import prepared!
Prepared opslevel_team_tag for import
opslevel_team_tag.team_tag_1: Refreshing state... [id=Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA:Z2lkOi8vb3BzbGV2ZWwvVGFnLzgyNjU0OTMw]
Import successful!
The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth …
```
=> fix terraform import opslevel_team_tag resources

.changes/unreleased/Bugfix-20240607-084851.yaml, opslevel/resource_opslevel_check_base.go, opslevel/resource_opslevel_check_tool_usage.go, opslevel/terraform_type_conversions.go, tests/remote/check_tool_usage.tftest.hcl
Fix this:
```tf
│ Error: Value Conversion Error
│ 
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│ 
│ Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
│ 
│ Path: tool_url_predicate
│ Target Type: opslevel.PredicateModel
│ Suggested `types` Type: basetypes.ObjectValue
│ Suggested Pointer Type: *opslevel.PredicateModel
```
PredicateModel has useful functions that remain. The schema now accepts ObjectValues instead and Terraform understands how to interpret these better than a custom struct with tfsdk tags.
```tf
resource "opslevel_check_tool_usage" …
```
=> convert Predicate types to ObjectValue in opslevel_check_tool_usage

.changes/unreleased/Feature-20240612-112423.yaml, examples/data-sources/opslevel_scorecard/data-source.tf, opslevel/datasource_opslevel_scorecard.go, opslevel/datasource_opslevel_scorecards_all.go, tests/local/datasource_scorecard.tftest.hcl, tests/remote/scorecard.tftest.hcl
[Add Categories field to Scorecard datasource](https://github.com/OpsLevel/team-platform/issues/388)
Add categories field to both `opslevel_scorecard` and `opslevel_scorecards` datasources.
Add this field to relevant tests.
```tf
data "opslevel_scorecards" "all" {}
data "opslevel_scorecard" "one" {
identifier = "Z2lkOi8vb3BzbGV2ZWwvUnVicmljLzEzMTg"
}
resource "opslevel_check_has_documentation" "has_docs" {
name             = "foobarbaz"
enabled          = true
category         = data.opslevel_scorecard.one.categories[0].id
level            = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvMzcxMA"
owner            = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
filter           = "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzM1NzA"
notes            = "Optional additional info on why this check is run or how to fix it"
document_type …
```
=> add categories field to scorecard data sources

.changes/unreleased/Bugfix-20240618-103110.yaml, opslevel/resource_opslevel_filter.go
Multiple filter blocks created with a `for_each` loop fail on validation. If a predicate's `value` field is set via `each.key`, the value would be unknown at validation time. This should not be counted as invalid configuration.
```tf
resource "opslevel_filter" "first_party_services" {
for_each = toset(local.envs)
name     = "Test application (${each.key})"
predicate {
key            = "tags"
key_data       = "third-party"
type           = "does_not_equal"
value          = "true"
case_sensitive = true
}
predicate {
key            = "tags"
key_data       = "environment"
type           = "equals"
value          = each.key
case_sensitive = true
}
connective = "and"
}
locals {
envs = [
"development",
"sandbox",
"production",
]
}
```
```tf
│ Error: Invalid Attribute Configuration
│ 
│   with …
```
=> fix filter predicate validation when created with for_each loop

.changes/unreleased/Bugfix-20240626-140311.yaml, .changes/unreleased/Feature-20240624-160020.yaml, examples/resources/opslevel_infrastructure/resource.tf, examples/resources/opslevel_service/resource.tf, examples/resources/opslevel_team/resource.tf, opslevel/common.go, opslevel/import_utils.go, opslevel/resource_opslevel_infra.go, opslevel/resource_opslevel_service.go, opslevel/resource_opslevel_team.go, opslevel/terraform_type_conversions.go, opslevel/validators.go
[Combine reconcileAliases](https://github.com/OpsLevel/team-platform/issues/363)
Add `Config warning` when creating a resource with `aliases` where slug is missing.
Use new ReconcileAliases function from opslevel-go
```tf
resource "opslevel_infrastructure" "example" {
aliases = []
schema  = "Database"
owner   = opslevel_team.example.id
provider_data = {
account = "dev2"
}
name = "my-database"
})
}
resource "opslevel_service" "example" {
name    = "foo25"
aliases = []
description = "The test service"
framework   = "something fancy"
language    = "elixir"
lifecycle_alias = "beta"
tier_alias      = "tier_2"
owner           = opslevel_team.example.id
api_document_path             = "/swagger.json"
preferred_api_document_source = "PULL" //or "PUSH"
}
resource …
```
=> update reconcileAliases to use opslevel-go implementation

.changes/unreleased/Bugfix-20240703-133905.yaml, opslevel/resource_opslevel_domain.go, opslevel/terraform_type_conversions.go, opslevel/validators.go, tests/remote/domain.tftest.hcl, tests/remote/test.tfvars
```tf
resource "opslevel_domain" "example" {
name        = "Example Domain 123"
description = null
note        = null
}
```
```tf
+ create
+ resource "opslevel_domain" "example" {
+ aliases = (known after apply)
+ id      = (known after apply)
+ name    = "Example Domain 123"
}
opslevel_domain.example: Creating...
opslevel_domain.example: Creation complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvRW50aXR5T2JqZWN0LzI4MTUxMzc]
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
```tf
resource "opslevel_domain" "example" {
name        = "Example Domain 123" …
```
=> allow empty string for Domain description and note fields

.changes/unreleased/Bugfix-20240705-150620.yaml, .changes/unreleased/Feature-20240705-150956.yaml, Taskfile.yml, opslevel/resource_opslevel_filter.go, opslevel/resource_opslevel_property_definition.go, opslevel/resource_opslevel_rubric_level.go, opslevel/resource_opslevel_scorecard.go, opslevel/resource_opslevel_system.go, opslevel/resource_opslevel_team.go, opslevel/resource_opslevel_webhook_action.go, opslevel/terraform_type_conversions.go, tests/acc/terraform_type_conversions_test.go, tests/remote/property_definition.tftest.hcl, tests/remote/rubric_level.tftest.hcl, tests/remote/scorecard.tftest.hcl, tests/remote/service.tftest.hcl, tests/remote/system.tftest.hcl, tests/remote/team.tftest.hcl, tests/remote/webhook_action.tftest.hcl
In `opslevel_filter`, ensure `predicate.key_data` is not an empty string in the Terraform config.
Convert `OptionalStringValue()` to `StringValueFromResourceAndModelField()` for ambiguous Terraform config string fields that can be an empty string or null.
[task test-integration](https://github.com/OpsLevel/terraform-provider-opslevel/actions/runs/9813222207/job/27098796038)
=> add regression tests for known buggy optional string fields

.changes/unreleased/Feature-20240710-121237.yaml, opslevel/resource_opslevel_scorecard.go, tests/local/mock_resource/scorecard.tfmock.hcl, tests/local/resource_scorecard.tftest.hcl, tests/remote/scorecard.tftest.hcl
[Add category ids to scorecard resource](https://github.com/OpsLevel/team-platform/issues/418)
Add computed (returned from API) `categories` field to `scorecards`. This contains a list of the scorecard's category ids. Today there is always only one id but this leaves room for multiple category ids.
```tf
resource "opslevel_scorecard" "test" {
affects_overall_service_levels = true
name                           = "scorecard with a category"
owner_id                       = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
}
output "scorecard_categories" {
value = opslevel_scorecard.test.categories
}
```
```tf
+ create
+ …
```
=> add categories field to scorecard resource

.changes/unreleased/Bugfix-20240715-112534.yaml, opslevel/resource_opslevel_check_alert_source_usage.go, opslevel/resource_opslevel_check_base.go, opslevel/resource_opslevel_check_repository_file.go, opslevel/resource_opslevel_check_repository_grep.go, opslevel/resource_opslevel_check_repository_search.go, opslevel/resource_opslevel_check_service_ownership.go, opslevel/resource_opslevel_check_service_property.go, opslevel/resource_opslevel_check_tag_defined.go, opslevel/resource_opslevel_check_tool_usage.go
[Add StateUpgraders to Terraform provider](https://github.com/OpsLevel/team-platform/issues/421)
Adding `StateUpgrader`s to these resources:
Added v0 (old `v0.11.0`) schemas for checks. The "v0" base schema and generic predicate schemas are done.
```bash
git checkout tags/v0.11.0
git submodule deinit --all -f  
git submodule init
git submodule update
task setup-terraform
```
```tf
locals {
category_id = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvNjk3Nw"
level_id    = "Z2lkOi8vb3BzbGV2ZWwvTGV2ZWwvMzcxMA"
owner_id    = "Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xNzQzNA"
filter_id   = "Z2lkOi8vb3BzbGV2ZWwvRmlsdGVyLzM1NzA"
}
resource "opslevel_check_alert_source_usage" "test" {
alert_type = "datadog"
name       = "Import alert source usage check"
enabled    = false
category = local.category_id
filter   = …
```
=> add StateUpgrader for opslevel_check_service_ownership

MIGRATION.md
=> no need to touch Terraform state during migration

opslevel/resource_opslevel_check_alert_source_usage.go, opslevel/resource_opslevel_check_manual.go, opslevel/resource_opslevel_check_repository_file.go, opslevel/resource_opslevel_check_repository_grep.go, opslevel/resource_opslevel_check_repository_search.go, opslevel/resource_opslevel_check_service_ownership.go, opslevel/resource_opslevel_check_service_property.go, opslevel/resource_opslevel_check_tag_defined.go, opslevel/resource_opslevel_check_tool_usage.go, opslevel/resource_opslevel_infra.go
=> add null cases for StateUpgraders

.changes/unreleased/Bugfix-20240716-131900.yaml, opslevel/resource_opslevel_check_repository_search.go
Fix state upgrader logic due to copy paste typo....
=> fix state import of opslevel_check_repository_search

.changes/unreleased/Bugfix-20240731-084025.yaml, opslevel/validators.go
[opslevel_service: tag validation fails with datasource or variable](https://github.com/OpsLevel/terraform-provider-opslevel/issues/415)
Update `TagFormatValidator` so elements in set of `tags` do not fail when given input variables.
```tf
variable "test" {
type    = string
default = "bar"
}
resource "opslevel_service" "db" {
name = "Small Service"
tags = ["foo:${var.test}"]
}
```
Run `terraform validate` on this config file
```bash
> terraform validate
Success! The configuration is valid.
```
=> tags validation no longer fails when given input variables

Taskfile.yml
Add `task validate` - builds the latest local code then runs `terraform validate` in `workspace/`
=> add task validate for smoother validation development

opslevel/resource_opslevel_integration_aws.go
Updated need after `opslevel-go` update
=> set OwnershipTagKeys field explicit path after upstream update

examples/resources/opslevel_check_package_version/import.sh, examples/resources/opslevel_check_package_version/resource.tf, opslevel/provider.go, opslevel/resource_opslevel_check_package_version.go
Blockout package version check.
```tf
data "opslevel_rubric_category" "performance" {
filter {
field = "name"
value = "Performance"
}
}
data "opslevel_rubric_level" "bronze" {
filter {
field = "name"
value = "Bronze"
}
}
resource "opslevel_check_package_version" "example" {
name    = "foo"
enabled = true
category = data.opslevel_rubric_category.performance.id
level    = data.opslevel_rubric_level.bronze.id
package_constraint = "exists"
package_manager = "npm"
package_name = "leftpad"
}
```
```bash
+ resource "opslevel_check_package_version" "example" {
+ category           = "Z2lkOi8vb3BzbGV2ZWwvQ2F0ZWdvcnkvOTYw"
+ description        = (known after apply)
+ enabled            = true
+ id                 = (known after apply)
+ level …
```
=> Blockout package version check

.changes/unreleased/Feature-20240801-124310.yaml, examples/resources/opslevel_check_service_property/resource.tf, opslevel/resource_opslevel_check_service_property.go
Fixes issue where the service property check couldn't target a custom property
```tf
data "opslevel_rubric_category" "performance" {
filter {
field = "name"
value = "Performance"
}
}
data "opslevel_rubric_level" "bronze" {
filter {
field = "name"
value = "Bronze"
}
}
resource "opslevel_check_service_property" "example2" {
name    = "foo2"
enabled = true
category            = data.opslevel_rubric_category.performance.id
level               = data.opslevel_rubric_level.bronze.id
property            = "custom_property"
property_definition = "my_custom_property"
predicate = {
type  = "exists"
}
notes = "Optional additional info on why this check is run or how to fix it"
}
```
```bash
+ resource "opslevel_check_service_property" "example2" {
+ …
```
=> Add custom property check

tests/remote/filter_predicate_aliases.tftest.hcl, tests/remote/filter_predicate_framework.tftest.hcl, tests/remote/filter_predicate_language.tftest.hcl, tests/remote/filter_predicate_lifecycle_index.tftest.hcl, tests/remote/filter_predicate_name.tftest.hcl, tests/remote/filter_predicate_product.tftest.hcl, tests/remote/filter_predicate_properties.tftest.hcl, tests/remote/filter_predicate_tags.tftest.hcl, tests/remote/filter_predicate_tier_index.tftest.hcl, tests/remote/test.tfvars
a## Issues
[Predicates in filters can be cryptic](https://github.com/OpsLevel/team-platform/issues/433)
Second half of this [first predicate tests PR](https://github.com/OpsLevel/terraform-provider-opslevel/pull/424)
Add integration tests focusing on the following predicate filters:
- `aliases`
- `framework`
- `language`
- `lifecycle_index`
- `name`
- `product`
- `properties`
- `tags`
- `tier_index`
Note: `lifecycle_index` and `tier_index` are basically the same
`aliases`, `framework`, `language`, `name`, `product`, `properties` and `tags` are basically the same
```bash
task test-integration -- \
"-filter=filter_predicate_aliases.tftest.hcl" \
"-filter=filter_predicate_framework.tftest.hcl" \
"-filter=filter_predicate_language.tftest.hcl" \ …
```
=> add rest of filter predicate tests

.changes/unreleased/Feature-20240808-161107.yaml, examples/data-sources/opslevel_service_dependencies/data-source.tf, opslevel/datasource_opslevel_service_dependencies.go, opslevel/provider.go, opslevel/resource_opslevel_integration_azure_resources.go
[Add ability to get the dependencies and dependents of a given service via a datasource](https://github.com/OpsLevel/terraform-provider-opslevel/issues/345)
```tf
data "opslevel_service_dependencies" "by_alias" {
service = "sample_mobile_app"
}
data "opslevel_service_dependencies" "by_id" {
service = "Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS85MzMyOA"
}
output "found_by_alias" {
value = data.opslevel_service_dependencies.by_alias
}
output "found_by_id" {
value = data.opslevel_service_dependencies.by_id
}
```
```tf
data.opslevel_service_dependencies.by_id: Reading...
data.opslevel_service_dependencies.by_alias: Reading...
data.opslevel_service_dependencies.by_alias: Read complete after 1s
data.opslevel_service_dependencies.by_id: Read complete after 1s
+ found_by_alias = {
+ …
```
=> add opslevel_service_dependencies datasource

opslevel/resource_opslevel_check_repository_grep.go
This check type has a state upgrader but doesn't have a schema version.  This might break newly created checks with 1.2.x when they try to upgrade to this version.  But it is what it is at this point.  We'll have to recommend people delete and recreate repo grep checks made with 1.2.x
=> Missing the schema version for repo grep check

.changes/unreleased/Feature-20240821-131503.yaml, opslevel/datasource_opslevel_team.go, tests/remote/team.tftest.hcl
Part of [Add ability to query the slack channel ID of a contact method that is a slack channel](https://github.com/OpsLevel/team-platform/issues/298)
Add team Contact data to `opslevel_team` and `opslevel_teams` datasources
```tf
data "opslevel_team" "test" {
alias = "engineering"
}
output "team_contacts" {
value = data.opslevel_team.test.contacts
}
```
```tf
data.opslevel_team.test: Reading...
data.opslevel_team.test: Read complete after 0s [id=Z2lkOi8vb3BzbGV2ZWwvVGVhbS8xMDI0Mg]
+ team_contacts = [
+ {
+ address      = "#engineering"
+ display_name = "Slack Channel"
+ display_type = "Secondary"
+ external_id  = "<redacted>"
+ id           = "Z2lk<redacted>"
+ is_default   = true
+ type         = "slack"
},
]
You can apply this plan to save these new output values to …
```
=> team contacts list added to opslevel_team datasources

tests/remote/team_contact.tftest.hcl, tests/remote/team_contact/main.tf, tests/remote/team_contact/variables.tf
Resolves # (part of) [Add Integration Tests](https://github.com/OpsLevel/team-platform/issues/445)
=> test team_contact resource

tests/remote/property_assignment.tftest.hcl, tests/remote/property_assignment/main.tf, tests/remote/property_assignment/variables.tf, tests/remote/property_definition/outputs.tf, tests/remote/property_definition/variables.tf
Resolves # (part of) [Add Integration Tests](https://github.com/OpsLevel/team-platform/issues/445)
=> opslevel_property_assignment tests added

tests/remote/service_tag.tftest.hcl, tests/remote/tag.tftest.hcl, tests/remote/tag/main.tf, tests/remote/tag/variables.tf
Resolves # [Add missing Terraform integration tests for opslevel_tag](https://github.com/OpsLevel/team-platform/issues/458)
=> test opslevel_tag resource

tests/remote/service_tool.tftest.hcl, tests/remote/service_tool/main.tf, tests/remote/service_tool/variables.tf
Resolves # [Add missing Terraform integration tests for opslevel_service_tool](https://github.com/OpsLevel/team-platform/issues/457)
=> test opslevel_service_tool resource

tests/remote/infrastructure.tftest.hcl, tests/remote/infrastructure/main.tf, tests/remote/infrastructure/variables.tf
Resolves # [Add missing Terraform integration tests for opslevel_infrastructure](https://github.com/OpsLevel/team-platform/issues/456)
=> test opslevel_infrastructure resource

.changes/unreleased/Bugfix-20240829-100657.yaml, examples/resources/opslevel_check_package_version/resource.tf, opslevel/resource_opslevel_check_package_version.go, tests/remote/check_package_version.tftest.hcl, tests/remote/check_package_version/base_variables.tf, tests/remote/check_package_version/main.tf, tests/remote/check_package_version/variables.tf
Resolves # [Add missing Terraform integration tests for opslevel_check_package_version](https://github.com/OpsLevel/team-platform/issues/455)
=> test opslevel_check_package_version resource

.changes/unreleased/Bugfix-20240830-094953.yaml, examples/resources/opslevel_service_repository/resource.tf, opslevel/resource_opslevel_service_repository.go
Resolves #466 
API truncates trailing slash of value set in `base_directory` field of `opslevel_service_repository`
Add validation logic that prohibits a trailing slash on this field
```tf
resource "opslevel_service_repository" "foo" {
service    = data.opslevel_service.foo.id
repository = data.opslevel_repository.foo.id
name           = "Foo"
base_directory = "example"
}
```
```tf
Success! The configuration is valid.
```
```tf
resource "opslevel_service_repository" "foo" {
service    = data.opslevel_service.foo.id
repository = data.opslevel_repository.foo.id
name           = "Foo"
base_directory = "example/"
}
```
```tf
Error: Invalid Attribute Value Match
with opslevel_service_repository.foo,
on main.tf line 14, in resource "opslevel_service_repository" "foo":
14:   base_directory = …
```
=> validate against ending slash on base_directory field in opslevel_service_repository

tests/filter.tftest.hcl, tests/team.tftest.hcl, tests/user.tftest.hcl
Resolves #
Tests based on [terraform-opslevel-modules](https://github.com/OpsLevel/terraform-opslevel-modules/) modules fail after upstream renames
Update names in tests. Run `task test-release` and `task test-unreleased` ✅
=> rename test resources to match upstream changes

tests/check_alert_source_usage.tftest.hcl, tests/check_git_branch_protection.tftest.hcl, tests/check_has_documentation.tftest.hcl, tests/check_has_recent_deploy.tftest.hcl, tests/check_repository_file.tftest.hcl, tests/check_repository_grep.tftest.hcl, tests/check_repository_integrated.tftest.hcl, tests/check_repository_search.tftest.hcl, tests/check_tag_defined.tftest.hcl, tests/check_tool_usage.tftest.hcl
Resolves [#477](https://github.com/OpsLevel/team-platform/issues/477) - relies on [in progress upstream modules PR](https://github.com/OpsLevel/terraform-opslevel-modules/pull/19)
Run `task test-release` to test
=> refactor remaining check tests to use module repo

.changes/unreleased/Feature-20241007-131137.yaml, examples/resources/opslevel_integration_aws/resource.tf, opslevel/resource_opslevel_integration_aws.go, tests/remote/integration_aws/main.tf, tests/remote/integration_aws/variables.tf, tests/remote/integration_aws_all.tftest.hcl, tests/remote/integration_aws_min.tftest.hcl
Resolves [#505](https://github.com/OpsLevel/team-platform/issues/505)
=> add region_override field to opslevel_aws_integration resource

tests/check_alert_source_usage.tftest.hcl, tests/check_git_branch_protection.tftest.hcl, tests/check_has_documentation.tftest.hcl, tests/check_has_recent_deploy.tftest.hcl, tests/check_manual.tftest.hcl, tests/data/main.tf, tests/data/outputs.tf
=> update check_alert_source_usage test

opslevel/resource_opslevel_check_alert_source_usage.go, opslevel/resource_opslevel_check_base.go, opslevel/resource_opslevel_check_git_branch_protection.go, opslevel/resource_opslevel_check_has_documentation.go, opslevel/resource_opslevel_check_has_recent_deploy.go, opslevel/resource_opslevel_check_manual.go
Resolves #
Limiting this refactor to checks with recently updated tests
To test, run:
```bash
task test-unreleased -- "-filter=check_alert_source_usage.tftest.hcl" "-filter=check_git_branch_protection.tftest.hcl" "-filter=check_has_documentation.tftest.hcl" "-filter=check_has_recent_deploy.tftest.hcl" "-filter=check_manual.tftest.hcl"
```
=> check base refactor, part 1

.changes/unreleased/Bugfix-20241022-094434.yaml, opslevel/resource_opslevel_check_package_version.go, opslevel/terraform_type_conversions.go, tests/check_has_recent_deploy.tftest.hcl, tests/check_manual.tftest.hcl, tests/check_package_version.tftest.hcl
Resolves #
🎗️ Relies on this [terraform-opslevel-modules PR](https://github.com/OpsLevel/terraform-opslevel-modules/pull/34)
🎗️ Relies on this [opslevel-go PR](https://github.com/OpsLevel/opslevel-go/pull/485)
=> correctly update missing_package_result field in package version check

.changes/unreleased/Feature-20241022-094830.yaml, examples/resources/opslevel_alias/resource.tf, opslevel/helpers.go, opslevel/provider.go, opslevel/resource_opslevel_alias.go, tests/aliases.tftest.hcl
Resolves https://github.com/OpsLevel/team-platform/issues/496
Currently we have no unified way to handle Aliasable resources like we do for Taggable ones.  
Apply the same interface pattern that was done to Taggable resources but for Aliasable ones.
=> Add `opslevel_alias` resource

opslevel/resource_opslevel_integration_endpoint.go, tests/integration_endpoint.tftest.hcl
Resolves #
The new endpoint integration doesn't expose the webhook url to send events to
Add that as a computed field so the customer can get at it and use it
=> Add missing webhook url field

.changes/unreleased/Bugfix-20241105-154206.yaml, examples/resources/opslevel_service_dependency/import.sh, opslevel/resource_opslevel_service_dependency.go
Resolves [#518](https://github.com/OpsLevel/team-platform/issues/518)
=> fix service_dependency import and infinite apply bug

.changes/unreleased/Bugfix-20241107-140256.yaml, examples/resources/opslevel_service_repository/import.sh, opslevel/resource_opslevel_service_repository.go
Resolves [#537](https://github.com/OpsLevel/team-platform/issues/537)
`terraform import` on `opslevel_service_repository` was not working
Fix `terraform import` on `opslevel_service_repository` and also have it accept aliases or ids
=> fix import service_repository, accepts aliases or id

examples/resources/opslevel_service_relationship/import.sh, examples/resources/opslevel_service_relationship/resource.tf, opslevel/common.go, opslevel/provider.go, opslevel/resource_opslevel_service_relationship.go, tests/service_relationship.tftest.hcl
Resolves [#469](https://github.com/OpsLevel/team-platform/issues/469)
🎗️ Testing relies on [this PR](https://github.com/OpsLevel/terraform-opslevel-modules/pull/57)
=> add opslevel_service_relationship resource

docs/data-sources/property_definition.md, docs/data-sources/property_definitions.md, docs/resources/property_definition.md, examples/resources/opslevel_property_definition/resource.tf, opslevel/datasource_opslevel_property_definition.go, opslevel/datasource_opslevel_property_definitions_all.go, opslevel/resource_opslevel_property_definition.go, tests/local/datasource_property_definition.tftest.hcl, tests/local/mock_datasource/property_definition.tfmock.hcl, tests/local/mock_resource/property_definition.tfmock.hcl, tests/local/resource_property_definition.tftest.hcl, tests/local/resources.tf, tests/remote/property_assignment.tftest.hcl, tests/remote/property_definition.tftest.hcl, tests/remote/property_definition/variables.tf
Allows `PropertyDefinition.lockedStatus` to be configured using our Terraform Provider
=> Add lockedStatus to PropertyDefinition

opslevel/resource_opslevel_component_type.go
Resolves #
There is currently no ability to specify the icon for a component type
Add this ability like this
```tf
resource "opslevel_component_type" "mobile" {
...
icon = {
color = "#f759ab"
name  = "PhDeviceMobile"
}
...
}
```
=> Add icon settings to component type resource

opslevel/resource_opslevel_property_assignment.go
Resolves #
The documentation states that property assignment only works on the default "service" component type.
Fix the documentation after confirming it works
```tf
resource "opslevel_property_assignment" "environment" {
definition = "account_url"
owner      = "gitlab"
value      = jsonencode("hello")
}
```
```bash
+ resource "opslevel_property_assignment" "environment" {
+ definition = "pii"
+ id         = (known after apply)
+ locked     = (known after apply)
+ owner      = "gitlab"
+ value      = "true"
}
opslevel_property_assignment.environment: Creating...
opslevel_property_assignment.environment: Creation complete after 1s [id=Z2lkOi8vb3BzbGV2ZWwvU2VydmljZS8yNzQ3NTU:Z2lkOi8vb3BzbGV2ZWwvUHJvcGVydGllczo6RGVmaW5pdGlvbi8xMTk4]
Apply complete! …
```
=> Improve docs and error handling

docs/resources/scorecard.md
Resolves #
The current documentation example for adding checks to a scorecard uses the wrong ID for the check creation
Fix the documentation example to use the category id for creating a check
=> Fix bad docs

.changes/unreleased/Fixed-20250502-101005.yaml, opslevel/resource_opslevel_service_repository.go
Resolves #573
When a service respository goes missing we error instead of trying to recreate it
In the read function nullify the ID so that terraform will try to re-create it.
=> Add graceful handling of missing service repository on service
